### PR TITLE
Fixed a permissions problem in bootstrap and new scripts for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by jariza**
A "sudo" was missing while Setting up EPEL Repo.
Added init and script files for Ubuntu 14.04

### CODE REVIEW

**Comment by fgalan** [comment]
It seems this PR is based on the https://github.com/telefonicaid/fiware-orion/pull/679 from @cquijano . Now that PR #679 has been published in develop, could you update `jariza:develop` with `develop`, so your PR only includes the new additions, please? Thanks!

**Comment by jariza** [comment]
I think it's done :)

**Comment by fgalan** [comment]
LGTM

**Comment by LeandroGuillen** [comment]
LGTM

**Comment by fgalan** [comment]
Merged. Thank for your contribution!

**Pull request merged**
