### PR TITLE
mongo driver migration to an officially supported one + moving Orion to CentOS 8

### PR DESCRIPTION
**Pull request by fgalan**
This PR is related with #3132 and provides the "wrapping modules" described in that issue.

At the present point, apart from a first version of the modules themselves (in the mongoDriver/ library) only a small part of the CB logic (in particular, the one related with subscription creation, update and retreival) has been migrated to use the new library.

The idea is to continue migrating more CB logic, enhancing mongoDriver/ in the process, if needed. This could be done either ini feature/3132_poc_isolating_driver_usage directly or as PR on that branch (contributions welcome! :)

Pay attention to the "FIXME OLD-DR" marks. They should be solved and removed before merging this PR into master.

Pending references to old driver outside mongoDriver (`grep '#include "mongo/' -R src/* | grep -v mongoDriver | wc -l`)

* 35

### CODE REVIEW

**Comment by fgalan** [comment]
Note that we have some part of CB using old mongo::BSON* classes and the other using orion::BSON* classes, we keep to separate connection pools:

```
$ contextBroker -fg -logLevel DEBUG -t 100 -logForHumans | grep "Connection info"
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[129]: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@12:46:59  mongoConnectionPool.cpp[116]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
```

Eventually, the old one will be removed and only the one with orion:: will remain.

**Comment by fgalan** [comment]
At commit 287144b9a1876ed29f50fdf5ec1a43eeb53ad894 initial implementation of mongoDriver and following files migrated:

* src/lib/apiTypesV2/HttpInfo.cpp
* src/lib/apiTypesV2/HttpInfo.h
* src/lib/mongoBackend/MongoCommonSubscription.cpp
* src/lib/mongoBackend/MongoCommonSubscription.h
* src/lib/mongoBackend/MongoCommonUpdate.cpp
* src/lib/mongoBackend/MongoGlobal.cpp (not fully)
* src/lib/mongoBackend/MongoGlobal.h (not fully)
* src/lib/mongoBackend/mongoCreateSubscription.cpp
* src/lib/mongoBackend/mongoGetSubscriptions.cpp
* src/lib/mongoBackend/mongoSubCache.cpp (probably not fully)
* src/lib/mongoBackend/mongoSubCache.h (probably not fully)
* src/lib/mongoBackend/mongoUpdateSubscription.cpp

Functional tests log:

```
Total test time: 3321.71 seconds

WARNING: 5 test cases disabled:
  o  2: 0000_bad_requests/exit.test
  o  30: 0000_ipv6_support/ipv4_only.test
  o  31: 0000_ipv6_support/ipv6_only.test
  o  390: 0917_queryContext_behaves_differently/query_with_and_without_forwarding.test
  o  625: 1310_suspect_200OK/suspect_200OK.test

```

**Comment by fgalan** [comment]
At commit c3895798ea449bf5e76a230025f992bbe1574a5c, almost old the code migrated (only some parts in MongoGlobal remain):

* src/lib/apiTypesV2/HttpInfo.cpp
* src/lib/cache/subCache.h
* src/lib/mongoBackend/MongoCommonRegister.cpp
* src/lib/mongoBackend/MongoCommonRegister.h
* src/lib/mongoBackend/MongoCommonUpdate.cpp
* src/lib/mongoBackend/MongoCommonUpdate.h
* src/lib/mongoBackend/MongoGlobal.cpp (not fully)
* src/lib/mongoBackend/MongoGlobal.h (not fully)
* src/lib/mongoBackend/compoundResponses.cpp
* src/lib/mongoBackend/compoundResponses.h
* src/lib/mongoBackend/compoundValueBson.cpp
* src/lib/mongoBackend/compoundValueBson.h
* src/lib/mongoBackend/dateExpiration.cpp
* src/lib/mongoBackend/dateExpiration.h
* src/lib/mongoBackend/location.cpp
* src/lib/mongoBackend/location.h
* src/lib/mongoBackend/mongoDiscoverContextAvailability.cpp
* src/lib/mongoBackend/mongoGetSubscriptions.cpp
* src/lib/mongoBackend/mongoQueryTypes.cpp
* src/lib/mongoBackend/mongoRegisterContext.cpp
* src/lib/mongoBackend/mongoRegistrationCreate.cpp
* src/lib/mongoBackend/mongoRegistrationDelete.cpp
* src/lib/mongoBackend/mongoRegistrationGet.cpp
* src/lib/mongoBackend/mongoSubCache.cpp
* src/lib/mongoBackend/mongoUpdateSubscription.cpp
* src/lib/ngsi/ContextAttribute.cpp
* src/lib/ngsi/ContextAttribute.h
* src/lib/ngsi/ContextElementResponse.cpp
* src/lib/ngsi/ContextElementResponse.h
* src/lib/ngsi/Metadata.cpp
* src/lib/ngsi/Metadata.h
* src/lib/rest/StringFilter.cpp
* src/lib/rest/StringFilter.h

Pending references to old driver outside mongoDriver (`grep '#include "mongo/' -R src/* | grep -v mongoDriver | wc -l`)

* 8

Functional tests log (from [travis](https://travis-ci.org/github/telefonicaid/fiware-orion/jobs/712627747)):

```
Total test time: 2548.58 seconds

WARNING: 5 test cases disabled:
  o  2: 0000_bad_requests/exit.test
  o  30: 0000_ipv6_support/ipv4_only.test
  o  31: 0000_ipv6_support/ipv6_only.test
  o  390: 0917_queryContext_behaves_differently/query_with_and_without_forwarding.test
  o  625: 1310_suspect_200OK/suspect_200OK.test
```

Unit test are expected to fail. Probably it is the same problem at commit 287144b9a1876ed29f50fdf5ec1a43eeb53ad894, solved using DISABLED.
However, we are not paying too much attention to this by the moment, we'll fix one the new driver
gets in place.

**Comment by fgalan** [comment]
At commit 7df0fb4, old code migrated.

Pending references to old driver outside mongoDriver (`grep '#include "mongo/' -R src/* | grep -v mongoDriver | wc -l`)

* 0

In addition, the following files has been removed from mongoBackend (no longer used):

* mongoConnectionPool.cpp|h
* connectionOperations.cpp|h
* safeMongo.cpp|h

With regards to [this previous comment](https://github.com/telefonicaid/fiware-orion/pull/3622#issuecomment-583375766) now the situation is:

```
$ contextBroker -fg -logLevel DEBUG -t 100 -logForHumans | grep "Connection info"
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000
DEBUG@13:50:23  mongoConnectionPool.cpp[117]: orion:: Connection info: dbName='orion', rplSet='', timeout=4666723172467343.000000

```

Functional tests log (https://travis-ci.org/github/telefonicaid/fiware-orion/jobs/713271841)):

```
Total test time: 2510.69 seconds

WARNING: 5 test cases disabled:
  o  2: 0000_bad_requests/exit.test
  o  30: 0000_ipv6_support/ipv4_only.test
  o  31: 0000_ipv6_support/ipv6_only.test
  o  390: 0917_queryContext_behaves_differently/query_with_and_without_forwarding.test
  o  625: 1310_suspect_200OK/suspect_200OK.test
```

So the codebase is now ready to start with the driver migration work :) That will be done in a branch of feature/3132_poc_isolating_driver_usage

The following tasks are deferred after driver migration:

* Enable some functions in connectionOperations.cpp, related with write concern (setWriteConcern, getWriteConern) and auth (connectionAuth). By the moment, Orion cannot authenticat on MongoDB nor change de write cocern.
* Re-enable de unit tests
* Review all remaining FIXME OLD-DR comments. Many of them are related with usage of the streaming API

**Comment by fgalan** [comment]
Stage one done in Stage 1 done in PR https://github.com/telefonicaid/fiware-orion/pull/3772

Note that in that PR we are the C official driver instead of the C++ official driver. Originally the plan was to use the C++ driver. However, at the end we have used the C driver given the following reasons:

* We didn't manage to compile the new C++ driver in CentOS 7 (probably due to the driver is using "modern C++" and the gcc compiler in
  CentOS 7 is too old)
* The C++ driver is in fact based in mongo C driver (which is installed as a prerequeriment of it). Thus, using mongo C driver directly
  removes a layer of software.
* The high-level abstractions that C++ driver could be providing are in fact provided by our own mongoDriver/ module. We don't need
  the C++ driver to provide such abstractions.

**Comment by fgalan** [comment]
Having completed stage 1 (the most difficult one :), the plan from now on is as follows. Each stage in the plan will be done in a separate PR (using task/3132_* pull branch as branch of this feature/3132_poc_isolating_driver_usage)

- [ ] Stage 2: disable mongo unit tests (thus removing the old legacy driver from all the code base) and lint fixes to make GitActions happy again (i.e. "all green" in this PR branch).
- [ ] Stage 3: work on the pending FIXME OLD-DR marks. Those not addressable at this moment will be moved to issues. Just to remember some of them:
   * setWriteConcern
   * getWriteConern
   * connectionAuth
- [ ] Stage 4: docker/Dockerfile to replace driver (in addition, maybe we can move to CentOS 8, taking into account the feedback in https://github.com/telefonicaid/fiware-orion/issues/3764) 
- [ ] Stage 5: modify documentation, specially (non exahustive list):
    * development manual: to include the new mongoDriver description
    * performance tunning document: to explain the mongoc-stat command
    * build from sources document
- [ ] Stage 6: CHANGES_NEXT_RELEASE adjustments & final minor cleanup

After merging this PR #3622, some additional tasks have to be done:

- [ ] Remove old driver from Dockerfile for CI

**Comment by fgalan** [comment]
Due to some problems in stage 2 (during PR #3790) I needed to "branch" a CI image for regression of this work, with label `:rpm8` and independent of the existing `:rpm7` (which will be removed at the end).

**Review by mapedraza — COMMENTED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does changes in some .md files that are also in the Japanese translation. It would be great if you could have a look and do a PR on this PR (i.e. a branch of feature/3132_poc_isolating_driver_usage branch) with the modifications.

In addition, it would be also great if you could review in that PR the procedures for installing Orion:

* In Ubuntu (doc/manuals/admin/build_source.md#ubuntu-1804-lts), taking into account the new driver and the move to MongoDB 4.4. I did some early modifications on the documentation, but not sure if they are complete and a review from your side would be great.
*  In Raspberry Pi (docker/raspberry_pi.md and docker/raspberry_pi.jp.md). Probably this ones don't need too much adaptation, as they are based in Orion running in docker (and Dockefile has been already adapted by me in feature/3132_poc_isolating_driver_usage branch). Maybe just change `docker build --build-arg=centos7 -t orion .` to `docker build --build-arg=centos8 -t orion .` ?

Thanks you very much in advance!

**Comment by fisuda** [comment]
@fgalan I updated Japanese documentation and sent the PR #3811. It would be great if you could review it.

And, I will build and test Orion 2.6.0-next and new mongo driver with this branch on Ubuntu 18.04 and Raspberry Pi. At the moment I have no environment to do it. I must set up an environment. Please give me some time.

Best regards,

**Comment by fgalan** [comment]
> @fgalan I updated Japanese documentation and sent the PR #3811. It would be great if you could review it.

Thanks for your prompt answer!

> And, I will build and test Orion 2.6.0-next and new mongo driver with this branch on Ubuntu 18.04 and Raspberry Pi. At the moment I have no environment to do it. I must set up an environment. Please give me some time.

No problem at all. Take your time :) Thanks!

**Comment by fgalan** [comment]
@fisuda given the late addition of `-dbDisableRetryWrites` CLI parameter in https://github.com/telefonicaid/fiware-orion/pull/3622/commits/c86abd316d8e62ccd1ac29f7d3248e9984d72358 commit, some .md files were modified. Could you sync the Japanese translation with an additional PR to this branch, please?

Thanks!

**Comment by fisuda** [comment]
I sent PR #3813 to add Japanese documentation about -dbDisableRetryWrites CLI. It would be great if you could review it.

Thank you.

**Comment by fisuda** [comment]
> * In Ubuntu (doc/manuals/admin/build_source.md#ubuntu-1804-lts), taking into account the new driver and the move to MongoDB 4.4. I did some early modifications on the documentation, but not sure if they are complete and a review from your side would be great.

I sent a PR https://github.com/telefonicaid/fiware-orion/pull/3819. It updataes the procedure to directly run Orion on Ubuntu (amd64 and aarch64). It would be great if you could review this PR.

**Comment by fgalan** [comment]
> 
> 
> > * In Ubuntu (doc/manuals/admin/build_source.md#ubuntu-1804-lts), taking into account the new driver and the move to MongoDB 4.4. I did some early modifications on the documentation, but not sure if they are complete and a review from your side would be great.
> 
> I sent a PR #3819. It updataes the procedure to directly run Orion on Ubuntu (amd64 and aarch64). It would be great if you could review this PR.

Merged. Thanks!

That covers the first item. Regarding the second item:

>     * In Raspberry Pi (docker/raspberry_pi.md and docker/raspberry_pi.jp.md). Probably this ones don't need too much adaptation, as they are based in Orion running in docker (and Dockefile has been already adapted by me in feature/3132_poc_isolating_driver_usage branch). Maybe just change `docker build --build-arg=centos7 -t orion .` to `docker build --build-arg=centos8 -t orion .` ?

It is not needed any adaptation in documents at the end?

**Comment by fisuda** [comment]
I'm work on the second item. I will send a PR for updating the documentation.

**Comment by fisuda** [comment]
> * In Raspberry Pi (docker/raspberry_pi.md and docker/raspberry_pi.jp.md). Probably this ones don't need too much adaptation, as they are based in Orion running in docker (and Dockefile has been already adapted by me in feature/3132_poc_isolating_driver_usage branch). Maybe just change `docker build --build-arg=centos7 -t orion .` to `docker build --build-arg=centos8 -t orion .` ?

I sent a PR #3825. It updates documentation to support CentOS 8 aarch64 for Raspberry Pi. It would be great if you could review this PR.

**Comment by fgalan** [comment]
06d93e5 is a "candidate commit" to merge this PR.

Valgrind test pass:

```
$ ./valgrindTestSuite.sh
...
10 functional tests failed (not a leak, just a func-test failure):
   015: get_entity_dates_with_options.test (exit code 1)
   028: https.test (exit code 1)
   352: attribute_dates.test (exit code 1)
   356: filter_attr_datemodified_sub.test (exit code 1)
   362: filter_datecreated_sub.test (exit code 1)
   365: get_entity_dates.test (exit code 1)
   516: sub_from_active_to_fail.test (exit code 1)
   800: 2064_attrs_blacklist_complex.test (exit code 1)
   923: 2750_reset_metrics.test (exit code 1)
   1156: log_notifications.test (exit code 1)
---------------------------------------

Total test time: 21448.25 seconds (357 minutes)
Great, all valgrind tests ran without any memory leakage
```

Functional tests with cache:

TBD

Functional test without cache:

TBD

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
Several issues as been created as a consequence of the work on this PR, in some way or another (some of them are technical debt, some others are ideas for improvements).  In particular these ones:

* https://github.com/telefonicaid/fiware-orion/issues/3794
* https://github.com/telefonicaid/fiware-orion/issues/3789
* https://github.com/telefonicaid/fiware-orion/issues/3788
* https://github.com/telefonicaid/fiware-orion/issues/3787
* https://github.com/telefonicaid/fiware-orion/issues/3786
* https://github.com/telefonicaid/fiware-orion/issues/3785
* https://github.com/telefonicaid/fiware-orion/issues/3775
* https://github.com/telefonicaid/fiware-orion/issues/3774

**Comment by fgalan** [comment]
The merging of this PR is an important milestone in the Orion Context Broker development. We are getting rid of the old legacy driver (a [very toxic and dangerous dependency](https://stackoverflow.com/a/46818981/1485926) that has been around for too many years) and start using an officially supported one (the Mongo C driver).

Special thanks to @mapedraza and @fisuda for their contributions to this PR's branch. Also, special thanks to @bazile-clyde @kevinAlbs, from the MongoDB team, to help me to understand how the Mongo C driver works :)

**Pull request merged**
