### PR TITLE
REMOVE center HTML tags in NGSIv1 spec .apib

### PR DESCRIPTION
**Pull request by fgalan**

### CODE REVIEW

**Comment by kzangeli** [comment]
<center> was depracated from HTML many years ago.
This modification was just to remove garbage (as the center stuff is already taken care of by CSS), or does the actual layout change?

Apart from that question, LGTM

**Comment by fgalan** [comment]
Removing `<center>` is due to it breaks a FIWARE tool to generate documentation (FABRE).

**Comment by kzangeli** [comment]
ok, perfect.

Again, LGTM

**Comment by fgalan** [comment]
Waiting from @jmcanterafonseca LGTM

**Comment by jmcanterafonseca** [comment]
LGTM

**Pull request merged**
