### PR TITLE
FIX blocked worker when MQTT broker is out (master)

### PR DESCRIPTION
**Pull request by fgalan**
Backport of PR #4276 (release/3.8.0) for master branch

### CODE REVIEW

**Review by mrutid — APPROVED** [review]
LGTM

**Review by mrutid — APPROVED** [review]
LGMT

**Comment by mrutid** [comment]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does a slight modification to .md documentation. It would be great if you would sync into the Japanese translation, please. Thanks!

**Pull request merged**
