### PR TITLE
MongoDB 6.0

### PR DESCRIPTION
**Pull request by fgalan**
Similar to PR https://github.com/telefonicaid/fiware-orion/pull/4331, just to check if we can take the MongoDB even newer...

- [x] GitActions
- [x] Documentation
- [x] docker/ stuff
- [x] CNR

### CODE REVIEW

**Comment by fgalan** [comment]
Overpassed by PR https://github.com/telefonicaid/fiware-orion/pull/4331. Closing.

**Comment by fgalan** [comment]
The migration from mongo to mongosh has raised that tests in test/functionalTest/cases/3442_ngsiv1_interop_location_fix/ were incorrect (`find()` was used in a way only one entity was shown in the test, wrongly existing two ones). They has been fixed in this PR.

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does some modifications to files that have a counterpart in the Japanese translation. It would be great if you could upgrade them in a PR, please. Thanks in advance!

**Comment by fisuda** [comment]
I sent the PR #4457. Thanks.

**Pull request merged**
