### PR TITLE
add back mongo

### PR DESCRIPTION
**Pull request by wistefan**
removing mongo from the ci image seems to also remove the mongo client, required for running the functional test. The fail in other branches because of that.

### CODE REVIEW

**Comment by fgalan** [comment]
mongo shell should be included in the `mongodb-org-shell` package. So probably the only changes needed are the ones in:

* Recover the mongodb.repo file (maybe moving version 3.6 -> 4.0?)
* Recover the `ADD` line for that file in Dockerhub

I think the other chagnes in the PR are not needed. Could you test please?

**Comment by wistefan** [comment]
> mongo shell should be included in the `mongodb-org-shell` package. So probably the only changes needed are the ones in:
> 
>     * Recover the mongodb.repo file (maybe moving version 3.6 -> 4.0?)
> 
>     * Recover the `ADD` line for that file in Dockerhub
> 
> 
> I think the other chagnes in the PR are not needed. Could you test please?

Yes, I'll do

**Comment by wistefan** [comment]
There was an issue beside mongo, that failed the unit tests. It seems that the ci-image wasn't built for quite a while now and gmock now is not available under the used address anymore. I changed that and now it seems to work again.

**Review by fgalan — APPROVED** [review]
Great! LGTM

**Pull request merged**
