### PR TITLE
REMOVE ngsi9 URL paths

### PR DESCRIPTION
**Pull request by fgalan**
We have check that there are no longer used in production environments.

Hold on this PR until the final release candidate for Orion 3.8.0

### CODE REVIEW

**Comment by fgalan** [comment]
@fisuda this PR modifies some .md files in the English documentation. It would be great if you could sync in the Japanese translation. In this case, given this PR is in HOLD ON status (so it would take some time until we merge it) the PR could be done using remove/ngsi9-routes as base branch (so after merging it its content gets integrated into the present PR).

Thanks!

**Comment by fisuda** [comment]
I sent the PR #4242 to the [remove/ngsi9-routes](https://github.com/telefonicaid/fiware-orion/tree/remove/ngsi9-routes) branch. Thanks.

**Comment by mapedraza** [comment]
Should this dependency also be commented? 
https://github.com/telefonicaid/fiware-orion/blob/20a5092ee7f8b2de72e91786049b47683a551ac0/src/app/contextBroker/orionRestServices.cpp#L90

Since the only object created in this file is commented here?:
https://github.com/telefonicaid/fiware-orion/blob/20a5092ee7f8b2de72e91786049b47683a551ac0/src/app/contextBroker/orionRestServices.cpp#L465

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
