### PR TITLE
FIX add comment about Python interpreter in walkthrough_apiv2.md

### PR DESCRIPTION
**Pull request by fgalan**
Issue #4519 

CC: @ArqamFarooqui110719

### CODE REVIEW

**Comment by ArqamFarooqui110719** [comment]
LGTM

**Review by ArqamFarooqui110719 — APPROVED** [review]

**Comment by fgalan** [comment]
@fisuda this PR does a small modification in a English document. It would be great if you could do a PR to sync the Japanese translation, please. Thanks in advance!

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fisuda** [comment]
I sent the PR #4525. Thanks.

**Pull request merged**
