### PR TITLE
Possibly fixed the issue #3884

### PR DESCRIPTION
**Pull request by fgalan**
Comes from PR https://github.com/telefonicaid/fiware-orion/pull/4026. Issue #3884 

- [x] CNR
- [x] Ok from @jason-fox 

CC: @kzangeli

### CODE REVIEW

**Comment by fgalan** [comment]
@jason-fox this dockerhub image can be used to tests:

telefonicaiot/fiware-orion:issue3884

**Comment by jason-fox** [comment]
Tested using image `telefonicaiot/fiware-orion:issue3884`

```console
curl -L -X PATCH 'http://localhost:1026/v2/entities/Bell:001/attrs' \
-H 'fiware-service: openiot' \
-H 'fiware-servicepath: /' \
-H 'Content-Type: application/json' \
-H 'host: orion-proxy:1027' \
-H 'accept: application/json' \
-H 'connection: close' \
-H 'X-Nick-Name: cccccccc-good-0000-0000-000000000000' \
-H 'x-auth-token: 2ca8a58ec971bfc6b0bcda8443931883eb5900d5' \
-H 'X-Display-Name: ' \
-H 'X-Roles: [{\"id\":\"security-role-0000-0000-000000000000\",\"name\":\"Security Team\"}]' \
-H 'X-Organizations: []' \
-H 'X-Eidas-Profile: {}' \
-H 'X-App-Id: tutorial-dckr-site-0000-xpresswebapp' \
-H 'x-forwarded-for: ::ffff:172.18.1.7' \
--data-raw '{
  "ring": {
      "type" : "command",
      "value" : ""
  }
}'
```

No longer breaks the context-broker.

**Comment by fgalan** [comment]
> No longer breaks the context-broker.

Thanks! We interpreted it as a positive report so this PR can be know merged :)

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
