### PR TITLE
Improve coverage framework

### PR DESCRIPTION
**Pull request by fgalan**
Issue #4418 (and additional minor fixes)

### CODE REVIEW

**Comment by fgalan** [comment]
`make coverage` metrics, as example/reference:

imagen

```
Overall coverage rate:
  lines......: 82.4% (18566 of 22536 lines)
  functions..: 88.7% (1592 of 1794 functions)
```

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does some small modifications to doc/manuals/admin/build_source.md. It would be great if you could do a PR with the sync in the Japanese translation, pls. Thanks!

**Comment by fisuda** [comment]
I sent the PR #4608.
Thanks.

**Pull request merged**
