### PR TITLE
ADD tests to cover x-auth-token, fiware-service and fiware-servicepath propagation cases with custom notifications and subscriptions with filters

### PR DESCRIPTION
**Pull request by fgalan**
- [x] fiware-service cases
- [x] fiware-servicepath cases
- [x] docu (if applicable)

### CODE REVIEW

**Comment by fgalan** [comment]
Note that non-modificabilty of fiware-correlator and ngsiv2-attrsformat (https://fiware-orion.readthedocs.io/en/master/user/ngsiv2_implementation_notes/index.html#non-modifiable-headers-in-custom-notifications) is already covered by existing test case: cases/2937_self_notification_protection/nonmodifiable_headers.test

**Comment by fgalan** [comment]
Relevant documentation at:

* https://fiware-orion.readthedocs.io/en/master/user/ngsiv2_implementation_notes/index.html#non-modifiable-headers-in-custom-notifications
* NGSIv2 spec (http://telefonicaid.github.io/fiware-orion/api/v2/stable/) "Custom Notification" section

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR has modified one of the .md files. It would be great if you could synchronize the change in the Japanese translation, please. Thanks!

**Comment by fisuda** [comment]
I sent the PR #4037. I would be great if you could review it.
Thanks.

**Pull request merged**
