### PR TITLE
Support for supportedForwardingMode

### PR DESCRIPTION
**Pull request by fgalan**
Issue #3106

### CODE REVIEW

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR modifies some .md documentation files. It would be great if you could do a PR to upgrade the Japanese translation. Thanks!

**Comment by fgalan** [comment]
@wistefan tests passed on this PR

imagen

However, upon merging the PR, several flows were failing:

imagen

I wonder why this is happending... do you know what is going on, please? Is the GitHub Actions system somehow unstable?

**Comment by fgalan** [comment]
> I wonder why this is happending... do you know what is going on, please? Is the GitHub Actions system somehow unstable?

Maybe relevant, in the process of building the CI image (https://github.com/telefonicaid/fiware-orion/runs/1709208332) I see this error:

```
#10 39.09 No package mongodb-org-shell available.
```

Surprisingly, the CI build flow as markes ad "passed" even when a required package is missed...

**Comment by fgalan** [comment]
I re-launch the CI building flow and this time `No package mongodb-org-shell available` didn't appear. After that, I re-launched the failing flows in master and everything goes back to green.

Weird... maybe a temporal glitch in yum repository resoultion? Let's see how it behave from now on...

**Pull request merged**
