### PR TITLE
Fix a crash & add ftest to cover other reported cases

### PR DESCRIPTION
**Pull request by fgalan**
This PR:

* Provides a fix (a covering ftest) for issue #3603 
* Provides covering ftests for issues #3604, #3605, #3606 and #3608. In this case, we haven't been able to reproduce the case (so no fix is needed), but a test is included to cover the reported cases.
* Would be expanded with nex fixes and/or ftests when #3607 and #3609 gets clarified (some questions has been done in the referred issued). That's why it's now in WIP status.

@0xricksanchez it would be great if you could have a look to the .test in this PR to ensure they cover the cases you reported in the issues, pls. Thanks!

### CODE REVIEW

**Comment by fgalan** [comment]
> @0xricksanchez it would be great if you could have a look to the .test in this PR to ensure they cover the cases you reported in the issues, pls. Thanks!

Did you have a chance to do the checking, please?

Thanks!

**Comment by fgalan** [comment]
> * Would be expanded with nex fixes and/or ftests when #3607 and #3609 gets clarified (some questions has been done in the referred issued). That's why it's now in WIP status.

Update: with regards to #3607 this new commit caeb5dd32 adds a test case covering the cases (test/functionalTest/cases/3607_killer_request_apiv1/killer_request_apiv1_parsing_cases.test). As you can see, I'm being unable to reproduce the crash based in the inputs provided in that issue and what I get for each one of the three requests is an NGSI-v1 style error message:

```
{
    "errorCode": {
        "code": "400",
        "details": "JSON Parse Error",
        "reasonPhrase": "Bad Request"
    }
}
```

Mabye something is wrong in the added .test? It would be great if @0xricksanchez could have a look please?

With regards to the other issue, I'm still waiting for clarification, see https://github.com/telefonicaid/fiware-orion/issues/3609#issuecomment-600056170

**Comment by fgalan** [comment]
Recent commits in https://github.com/telefonicaid/fiware-orion/pull/3615/commits/9d8775d71a78168934da94d96e73e18a41a735e8 and https://github.com/telefonicaid/fiware-orion/pull/3615/commits/fbb27c4de7da3cdab6a262ffaf700e92ac976baa implement and maximum nesting limit (50 levels) so the 500 Internal Error due to MongoDB error is now transformed in a 400 Bad Request message with informative message.

**Comment by fgalan** [comment]
@fisuda this PR includes a small addition to one of the .md documentation files. It would be great if you could sync the Japanese translation. Thanks!

**Comment by fisuda** [comment]
Noted with thanks!

**Pull request merged**
