### PR TITLE
(JP) ADD documentation regarding new attrsFormat values and notifyOnMetadataChange

### PR DESCRIPTION
**Pull request by fisuda**
I added Japanese documentation regarding new attrsFormat values and notifyOnMetadataChange. It would be great if you could review this PR. Thanks.

### CODE REVIEW

**Comment by fgalan** [comment]
Maybe this PR could include also .md modifications derived from:

* PR https://github.com/telefonicaid/fiware-orion/pull/4298
   * database_model.md
* PR https://github.com/telefonicaid/fiware-orion/pull/4300
   * database_model.md
   * subscriptionCache.md

**Comment by fisuda** [comment]
I reverted .md modifications derived from then.

**Comment by fgalan** [comment]
> I reverted .md modifications derived from then.

I didn't realized that the modification were already there before posting my comment :O. I apologize, my comment was confusing...

Please, add them back again (it should be easy: just revert the revert of the commits).

**Comment by fisuda** [comment]
I reverted them again.

**Review by fgalan — APPROVED** [review]
Thanks! LGTM

**Pull request merged**
