### PR TITLE
Feature/update append by id acceptance test

### PR DESCRIPTION
**Pull request by iariasleon**

### CODE REVIEW

**Comment by fgalan** [comment]
LGTM (passing the ball to QA team for final LGTM + merge + delete branch)

**Comment by jcanonav** [comment]
LGTM

**Comment by fgalan** [comment]
Excepcionally, this PR will be merged without review from @mcarracedo or @XavierVal , as they seem to be unavailable now to provide feedback.

**Comment by fgalan** [comment]
> Excepcionally, this PR will be merged without review from @mcarracedo or @XavierVal , as they seem to be unavailable now to provide feedback.

I haven't spotted the LGTM from @jcanonav , sorry... with that, I think is ok from QA side.

**Pull request merged**
