### PR TITLE
Ws

### PR DESCRIPTION
**Pull request by fortizc**
Add a very preliminar websockets support for Orion

### CODE REVIEW

**Comment by fgalan** [comment]
LGTM

However, it seems it is not mergeable (probably your branch needs sync from telefonicaid:feature/1181_websockets)

**Comment by kzangeli** [comment]
It would be nice to see a functional test ...
Can curl handle websocks?

**Comment by fgalan** [comment]
An specific issue (https://github.com/telefonicaid/fiware-orion/issues/1672) address functional test. Take into account that the purpose of this PR is just land the code in the central repository, further works will be done after that.

**Comment by kzangeli** [comment]
ok to functests in another PR.

LGTM

**Pull request merged**
