### PR TITLE
Fix partial success HTTP status codes

### LINKED ISSUE #3054: Partial success HTTP status codes
for certain entity update operations, for instance, append attributes in strict mode, if one or more of the concerned attributes already exist, the operation will end up with a 422 error code, but any non-existent attribute will have been added to the entity. i.e something went well, something went bad ... 

Status code `422` could be changed by another HTTP status code that gives information to the client that the operation had a partial success, i.e. something went well but not all 

see 

https://stackoverflow.com/questions/8472935/http-status-code-for-a-partial-successful-request

### PR DESCRIPTION
**Pull request by chetan-NEC**
**Fix #3054** 

- Change response code for partially successful updated entities

### CODE REVIEW

**Comment by chetan-NEC** [comment]
Hi @fgalan, the branch has been upgraded.

**Comment by chetan-NEC** [comment]
Gentle reminder!

**Comment by chetan-NEC** [comment]
Hi @fgalan, Gentle reminder!

**Comment by chetan-NEC** [comment]
Hi @fgalan, I have achieved the desired functionality, but NGSIv1-related test cases have failed. 
So, do you have any suggestions? 
Thank you in advance for your time and assistance. I look forward to reading your response.

**Comment by chetan-NEC** [comment]
@fgalan, I spend lot of time to achieve the required functionality, but I really agree with your recommendation to close this PR.

**Comment by fgalan** [comment]
> @fgalan, I spend lot of time to achieve the required functionality, but I really agree with your recommendation to close this PR.

Your time has not been wasted :) It has been very useful to reach the conclusion about what to do with the issue, which is also very important.

Note also that even in the case we want to change the behaviour, the work would not be finished. New tests (the ones described [here](https://github.com/telefonicaid/fiware-orion/pull/4003#issuecomment-1011091034)) would need to be implemented, which would involve more effort (with uncertain result).

Having said that, if you have a proposal on how to fix the issue without involving backward compatibility issues, please go ahead with the suggestion. My proposal of closing the issue along with related PR is due to I don't see any good solution... but if somebody does please tell me about :)

Otherwise, please @chetan-NEC close PR #4266 and I'll go ahead with the remaning closing actions.

Thanks for your feedback!

**Comment by chetan-NEC** [comment]
Thanks for your feedback! 
I have closed the PR.

**Pull request closed without merging**
