### PR TITLE
includePayload feature (fixes issue #3272) (dup PR)

### PR DESCRIPTION
**Pull request by fgalan**
Porting PR https://github.com/telefonicaid/fiware-orion/pull/3683 from @Anjali-NEC to finish it myself. Related issue #3272

Note first commit in this PR is +806 +4. In the old PR is +815 -13 but there is +9 -9 offset due to differences in CHANGES_NEXT_RELEASE file.(+806 +4) + (9 -9) = (+815 - 13), so the porting seems to be ok.

### CODE REVIEW

**Comment by fgalan** [comment]
As author of the original implementation that I have modified, @Anjali-NEC it would be great if you could have a look to this PR and tell me if you find it ok or some some feedback, pls. My modifications are in commit e047d2f but maybe is easier to review to look to the whole PR ("Files" tab).

At the end I'm using `"payload": null` as "switch" to select the no-payload mode (as originally described in parent issue). I needed to expand JsonHelper and utilsParse modules with a couple of helper functions in the process.

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@Anjali-NEC the PR has been merged. However, if you have some feedback we can of course include it as a new PR.

**Comment by fgalan** [comment]
@fisuda this PR modifies some .md files. It would be great if you could sync the Japanese translation based on that, please. Thanks!

**Comment by fisuda** [comment]
I sent the PR #3853. It would be great if you could review it.

**Pull request merged**
