### PR TITLE
Remove proxyCoap and add rapidjson to ubuntu bootstrap script

### PR DESCRIPTION
**Pull request by LeandroGuillen**
Also clean leftovers from other times

### CODE REVIEW

**Comment by LeandroGuillen** [comment]
Ready for review

**Comment by fgalan** [comment]
Just to understand this PR a little bit... this PR will make the vagrant stuff (https://github.com/telefonicaid/fiware-orion/blob/develop/doc/manuals/vagrant.md) work again? (as far as I remember it is now in a "broken" state in develop).

**Comment by LeandroGuillen** [comment]
The Vagrant method is still not working, but the script is useful (for me, at least) for compiling orion in ubuntu.

And by the way Vagrant has been deprecated. The company behind it has created a newer and shinier thing. We should probably remove it ourselves from this repo as well.

**Comment by fgalan** [comment]
> We should probably remove it ourselves from this repo as well.

By the moment, could you "move" it to the archive/ directory? Not in this PR, of course, but in a next one.

**Comment by fgalan** [comment]
LGTM

**Pull request merged**
