### PR TITLE
Obsolete RPM generation for RHEL/CentOS 7 (they should move to 8 or being removed)

### PR DESCRIPTION
**Pull request by fgalan**
We have changed from RHEL/CentOS 7 to 8 in PR #3622 and this change makes obsolete some parts of the documentation that makes reference to https://nexus.lab.fiware.org/service/rest/repository/browse/el/7 (with ending "7"). I understand they should be changed to https://nexus.lab.fiware.org/service/rest/repository/browse/el/8 but before that, I would need confirmation from the FIWARE Foundation (the ones that own that server and develop the system to automatically build RPMs on it) about this.

As far as I understand, there are three possibilities:

1. Keep releasing RPMs, updating the build system and documentation to RHEL/CentOS 8
2. Remove the releasing of RPMs, thus removing all related documentation about it in the repository
3. Merge this PR as it is, leaving the FIXME marks and defer the problem for the future

@wistefan what do you think, please?

### CODE REVIEW

**Comment by fgalan** [comment]
People is having problems with Orion RPM installations, see https://stackoverflow.com/questions/68922565/error-when-trying-to-install-orion-context-broker-using-yum-in-centos

@wistefan @flopezag did you have opportunity of having a look to this? What's the status, please?

**Comment by wistefan** [comment]
I'm currently updating the RPM deployment job work again. Will be available in the next days.

**Comment by fgalan** [comment]
PR #3937 has been merged into this one. Thanks!

@wistefan should I understand additional PRs on this one will come to solve the current FIXME marks in the documentation?

**Comment by wistefan** [comment]
@fgalan No, no more PRs required. I was able to solve everything else inside the build system. The 3.2.0 release is now available:
https://nexus.lab.fiware.org/repository/el/repository/el/8/x86_64/release/contextBroker-3.2.0-1.x86_64.rpm

**Comment by fgalan** [comment]
> @fgalan No, no more PRs required. I was able to solve everything else inside the build system. The 3.2.0 release is now available:
> https://nexus.lab.fiware.org/repository/el/repository/el/8/x86_64/release/contextBroker-3.2.0-1.x86_64.rpm

I understand that at least references the following ocurrences should be changed:

* `https://nexus.lab.fiware.org/service/rest/repository/browse/el/7/x86_64/` -> `https://nexus.lab.fiware.org/service/rest/repository/browse/el/8/x86_64/` and that 
* `releasever=7` ->  `releasever=8`

I can do it if you prefer (it's an easy change, greep-driven ;), but I'd like to have a confirmation. Maybe I'm missing some other thing.

**Comment by wistefan** [comment]
> > @fgalan No, no more PRs required. I was able to solve everything else inside the build system. The 3.2.0 release is now available:
> > https://nexus.lab.fiware.org/repository/el/repository/el/8/x86_64/release/contextBroker-3.2.0-1.x86_64.rpm
> 
> I understand that at least references the following ocurrences should be changed:
> 
>     * `https://nexus.lab.fiware.org/service/rest/repository/browse/el/7/x86_64/` -> `https://nexus.lab.fiware.org/service/rest/repository/browse/el/8/x86_64/`
> 
>     * `releasever=7` ->  `releasever=8`
> 
> 
> I can do it if you prefer (it's an easy change, greep-driven ;), but I'd like to have a confirmation. Maybe I'm missing some other thing.

Sorry, forgot the link in the do. Yes, that should be changed. 
The releasever=7 can be changed for clarity, but is set(and therefor unused here) inside the build job.

**Comment by fgalan** [comment]
>  The releasever=7 can be changed for clarity, but is set(and therefor unused here) inside the build job.

I think is used at this point: https://github.com/telefonicaid/fiware-orion/blob/master/ci/rpm8/build.sh#L366

**Comment by fgalan** [comment]
CentOS/RHEL version references fixed in commits 04176b9 and 29c7fc6

@wistefan it would be great if you could have a look to this PR and provide a LGTM if you find it find. If you find something missing to change, please tell me.

@fisuda it would be great if you could also have a look and provide LGTM. I have "blindly" touched the Japanese documents and maybe I have done some mistake or missing something.

Thanks!

**Comment by fisuda** [comment]
LGTM about Japanese documentation
Thanks.

**Comment by fgalan** [comment]
@wistefan @flopezag taking into account the upcoming FIWARE TSC on Orion, could you provide an status update of this PR (or be prepared to attend to the TSC and report at the meeting), please? Thanks!

**Comment by wistefan** [comment]
Please see: https://github.com/telefonicaid/fiware-orion/pull/4023

I fixed the mentioned links, sorry that it took so long. I was not able to reproduce it, until I figured out that they work for me because I'm logged in...

**Comment by fgalan** [comment]
The broken links mentioned in https://github.com/telefonicaid/fiware-orion/pull/3834#issuecomment-919199271 are now fixed. Great!

Let's wait first to merge PR #4003 before merging this PR.

**Review by fgalan — COMMENTED** [review]
LGTM

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
