### PR TITLE
Add "Authorization" in the list of Cors allowed headers (#4249)

### PR DESCRIPTION
**Pull request by chicco785**

### CODE REVIEW

**Comment by chicco785** [comment]
@fgalan looking at the code I realize you are propagating the `X-AUTH-TOKEN` header. Which I believe is an interesting functionality also for the OAuth tokens using the standard header. So, instead of duplicating the code to reproduce the functionality, the smartest way could be to set the name of this header via an environment variable, so that the same functionality can be shared without duplications. But I have no clue how to do that :)

**Comment by fgalan** [comment]
> @fgalan looking at the code I realize you are propagating the `X-AUTH-TOKEN` header. Which I believe is an interesting functionality also for the OAuth tokens using the standard header. So, instead of duplicating the code to reproduce the functionality, the smartest way could be to set the name of this header via an environment variable, so that the same functionality can be shared without duplications. But I have no clue how to do that :)

Unsure... but let's move it out of this PR into an independent issue so we can discuss there.

Could you create the issue, please? Thanks!

**Review by fgalan — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does modifications to some .md files. Not sure if they have equivalence in Japanese translation, in that case it would be great if you could sync the changes, please.

Thanks!

**Comment by fisuda** [comment]
I send the PR #4253. Thanks.

**Pull request merged**
