### PR TITLE
REFACTOR requestCompleted() logic

### PR DESCRIPTION
**Pull request by fgalan**
Issue #3738

### CODE REVIEW

**Comment by fgalan** [comment]
Review recomentation: use "Hide whitespace changes" setting to simpliify the review.

**Comment by kzangeli** [comment]
It's a little bit difficult to follow the diff but it looks good!

LGTM

**Review by kzangeli — APPROVED** [review]

**Comment by kzangeli** [comment]
With the new github feature to "ignore whitespace" the diff is very easy to follow.
Again, and this time for sure!
LGTM

**Comment by fgalan** [comment]
I did a valgrind pass in this PR:

```
6 functional tests failed (not a leak, just a func-test failure):
   367: attribute_dates.test (exit code 1)
   375: entity_dates_overridden_by_user_subs.test (exit code 1)
   380: get_entity_dates.test (exit code 1)
   532: sub_from_active_to_fail.test (exit code 1)
   533: sub_from_fail_to_active.test (exit code 1)
   623: subCacheThrottlingAndExpiration.test (exit code 1)
---------------------------------------

Total test time: 16926.47 seconds (282 minutes)
Great, all valgrind tests ran without any memory leakage

$ contextBroker --version | head -n 1
2.5.0-next (git version: 548d718935c5f2907fd028cdfbd8c7148e8dee46)
```

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Pull request merged**
