### PR TITLE
ADD custom notification json field additional tests

### PR DESCRIPTION
**Pull request by fgalan**
Additional tests for #2560 along with documentation improvements.

No CNR entry needed. This is already covered by current entry:

```
- Add: json field in httpCustom and mqttCustom subscriptions to implement JSON-based payloads in notifications (#2560)
```

### CODE REVIEW

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR modifies some .md files in the English documentation. It would be great if you could sync in the Japanese translation.

Thanks!

**Comment by fgalan** [comment]
(Maybe the sync for PR #4229 and PR #4239 could be done in the same PR)

**Comment by fisuda** [comment]
I sent the PR #4241. Thanks.

**Pull request merged**
