### PR TITLE
ADD support 'true' and 'false' literals (in addition to 'TRUE' and 'FALSE') in flag-like env vars

### PR DESCRIPTION
**Pull request by fgalan**

### CODE REVIEW

**Comment by kzangeli** [comment]
`paIsSet()` was recently updated to look also at env vars - you might want to add "true" as a valid option there too.

**Comment by fgalan** [comment]
> `paIsSet()` was recently updated to look also at env vars - you might want to add "true" as a valid option there too.

Done in 7cd8c384c. Thanks for the hint!

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does a small modification to one .md file. It would be great if you could upgrade the Japanese translation, please. Thanks!

**Comment by fisuda** [comment]
Noted with thanks!

**Pull request merged**
