### PR TITLE
FIX avoid valgrind false positives in modern OS

### PR DESCRIPTION
**Pull request by fgalan**
A solution for issue #3809

### CODE REVIEW

**Comment by fgalan** [comment]
Valgrind result:

```
...
2 tests leaked memory:
   270: 0706_direct_https_notifications/direct_https_notifications_no_accept_selfsigned.test (lost 4164 bytes, see direct_https_notifications_no_accept_selfsigned.valgrind.out)
   271: 0706_direct_https_notifications/direct_https_notifications.test (lost 4164 bytes, see direct_https_notifications.valgrind.out)
---------------------------------------



2 test cases show valgrind errors:
  028: https shows 2 valgrind errors
  737: subcache_typepattern shows 5 valgrind errors
---------------------------------------



3 functional tests failed (not a leak, just a func-test failure):
   015: get_entity_dates_with_options.test (exit code 1)
   515: sub_from_active_to_fail.test (exit code 1)
   606: subCacheThrottlingAndExpiration.test (exit code 1)
---------------------------------------

Total test time: 15017.52 seconds (250 minutes)
```

Let's see now if they are glitches...

**Comment by fgalan** [comment]
subcache_typepattern.test is a glitch. In an individual pass:

```
$ ./valgrindTestSuite.sh subcache_typepattern.test
vie 03 sep 2021 10:58:21 CEST
./valgrindTestSuite.sh: línea 215: cd: test/valgrind: No existe el fichero o el directorio
Test 001/1: 1853_typePattern_3a/subcache_typepattern ................................................................................................ OK (17.63 seconds)
Total test time: 17.76 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```

The other three failing tests aren't glitches.

**Comment by fgalan** [comment]
I have created issues for the still failing tests:

* https://github.com/telefonicaid/fiware-orion/issues/3924
* https://github.com/telefonicaid/fiware-orion/issues/3925

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
