### PR TITLE
FIX improve valgrindTestSuite.sh to detect invalid read and write errors

### PR DESCRIPTION
**Pull request by fgalan**
Based in part of PR https://github.com/FIWARE/context.Orion-LD/pull/1103

However, not sure if the loop logic is correct. Talking with @kzangeli about it...

### CODE REVIEW

**Comment by fgalan** [comment]
> Based in part of PR [FIWARE#1103](https://github.com/FIWARE/context.Orion-LD/pull/1103)

and in PR https://github.com/FIWARE/context.Orion-LD/pull/1105

**Review by kzangeli — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
Before merging, I have done some tests in master (i.e. without modifying yet the valingrinTestSuite.sh script).

-----------

With CB "good code", valgrindTestSuite execution:

```
(p3) fermin@debian11:~/src/fiware-orion/test/valgrind$ ./valgrindTestSuite.sh -fromIx 111 -toIx 111
mar 26 abr 2022 15:59:16 CEST
Run tests 111 to 111
./valgrindTestSuite.sh: línea 243: cd: test/valgrind: No existe el fichero o el directorio
Test 111/1300: 0000_ngsi10_update/delete_entity ..................................................................................................... OK (9.33 seconds)
Total test time: 10.40 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```

in the valgrind log file:

```
==143938== LEAK SUMMARY:
==143938==    definitely lost: 0 bytes in 0 blocks
==143938==    indirectly lost: 0 bytes in 0 blocks
==143938==      possibly lost: 1,104 bytes in 3 blocks
==143938==    still reachable: 3,015 bytes in 35 blocks
==143938==         suppressed: 0 bytes in 0 blocks
==143938== Reachable blocks (those to which a pointer was found) are not shown.
==143938== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==143938==
==143938== ERROR SUMMARY: 3 errors from 3 contexts (suppressed: 0 from 0)
```

------------------------

With CB hacked code to produce invalid write (but no leak):

```diff
diff --git a/src/lib/serviceRoutines/postUpdateContext.cpp b/src/lib/serviceRoutines/postUpdateContext.cpp
index 23bac4ee4..97b961535 100644
--- a/src/lib/serviceRoutines/postUpdateContext.cpp
+++ b/src/lib/serviceRoutines/postUpdateContext.cpp
@@ -538,6 +538,10 @@ std::string postUpdateContext
   Ngsiv2Flavour              ngsiV2Flavour
 )
 {
+  char* xP = (char*) malloc(10);
+  xP[10] = 'E';
+  free(xP);
+
   UpdateContextResponse*  upcrsP = &parseDataP->upcrs.res;
   UpdateContextRequest*   upcrP  = &parseDataP->upcr.res;
   std::string             answer;
```

valgrindTestSuite execution:

```
(p3) fermin@debian11:~/src/fiware-orion/test/valgrind$ ./valgrindTestSuite.sh -fromIx 111 -toIx 111
mar 26 abr 2022 16:00:17 CEST
Run tests 111 to 111
./valgrindTestSuite.sh: línea 243: cd: test/valgrind: No existe el fichero o el directorio
Test 111/1300: 0000_ngsi10_update/delete_entity ..................................................................................................... FAILED (valgrind errors: 2). Check delete_entity.valgrind.out for clues


1 test cases show valgrind errors:
  111: delete_entity shows 2 valgrind errors
---------------------------------------

Total test time: 11.03 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```

in the valgrind log file:

```
==145995== 2 errors in context 1 of 4:
==145995== Thread 9 MHD-connection:
==145995== Invalid write of size 1
==145995==    at 0x27CDB3: postUpdateContext(ConnectionInfo*, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, ParseData*, Ngsiv2Flavour) (postUpdateContext.cpp:542)
==145995==    by 0x2D0885: restService(ConnectionInfo*, RestService*) (RestService.cpp:700)
==145995==    by 0x2D1135: orion::requestServe[abi:cxx11](ConnectionInfo*) (RestService.cpp:774)
==145995==    by 0x2CA5DC: connectionTreat(void*, MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**) (rest.cpp:1644)
==145995==    by 0x43CC3E: call_connection_handler (connection.c:2220)
==145995==    by 0x43E5A7: MHD_connection_handle_idle (connection.c:3513)
==145995==    by 0x4402CD: call_handlers (daemon.c:1215)
==145995==    by 0x4433C0: thread_main_handle_connection (daemon.c:2144)
==145995==    by 0x4B25EA6: start_thread (pthread_create.c:477)
==145995==    by 0x5320DEE: clone (clone.S:95)
==145995==  Address 0xad94caa is 0 bytes after a block of size 10 alloc'd
==145995==    at 0x483877F: malloc (vg_replace_malloc.c:307)
==145995==    by 0x27CDA0: postUpdateContext(ConnectionInfo*, int, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, ParseData*, Ngsiv2Flavour) (postUpdateContext.cpp:541)
==145995==    by 0x2D0885: restService(ConnectionInfo*, RestService*) (RestService.cpp:700)
==145995==    by 0x2D1135: orion::requestServe[abi:cxx11](ConnectionInfo*) (RestService.cpp:774)
==145995==    by 0x2CA5DC: connectionTreat(void*, MHD_Connection*, char const*, char const*, char const*, char const*, unsigned long*, void**) (rest.cpp:1644)
==145995==    by 0x43CC3E: call_connection_handler (connection.c:2220)
==145995==    by 0x43E5A7: MHD_connection_handle_idle (connection.c:3513)
==145995==    by 0x4402CD: call_handlers (daemon.c:1215)
==145995==    by 0x4433C0: thread_main_handle_connection (daemon.c:2144)
==145995==    by 0x4B25EA6: start_thread (pthread_create.c:477)
==145995==    by 0x5320DEE: clone (clone.S:95)
==145995==
==145995== ERROR SUMMARY: 5 errors from 4 contexts (suppressed: 0 from 0)
```

------------------

So it seems valgrindSuiteTest.sh is reporting invalidad read/write errors even without explicitly grep-ing for them...

**Comment by fgalan** [comment]
With the changes in the PR to valgrindTestSuite.sh:

```
(p3) fermin@debian11:~/src/fiware-orion/test/valgrind$ ./valgrindTestSuite.sh -fromIx 111 -toIx 111
mar 26 abr 2022 16:10:15 CEST
Run tests 111 to 111
./valgrindTestSuite.sh: línea 243: cd: test/valgrind: No existe el fichero o el directorio
Test 111/1300: 0000_ngsi10_update/delete_entity ..................................................................................................... FAILED (valgrind errors: 4). Check delete_entity.valgrind.out for clues


1 test cases show valgrind errors:
  111: delete_entity shows 4 valgrind errors
---------------------------------------

Total test time: 11.22 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```

Maybe the extra checks included in the PR is over-reporting errors?

**Comment by fgalan** [comment]
> Maybe the extra checks included in the PR is over-reporting errors?

After discussing this with @kzangeli at skype, it seems this was a "false" alarm. This PR is going to be closed ("mirroring" the rollback in this PR https://github.com/FIWARE/context.Orion-LD/pull/1106/files)

**Pull request closed without merging**
