### PR TITLE
FIX many OLD-DR issues (bis)

### PR DESCRIPTION
**Pull request by fgalan**
(This PR is one of the stages of the the bigger PR #3622)

We have passed from 44 OLD-DR marks to 15 OLD-DR. The work will continue after this PR.

### CODE REVIEW

**Comment by fgalan** [comment]
Some of the "FIXME OLD-DR" has been moved to issues without leaving a "FIXME #XXXX" mark in the code due to they are too broad and no specific part in the code is associated. These ones:

* https://github.com/telefonicaid/fiware-orion/issues/3785
* https://github.com/telefonicaid/fiware-orion/issues/3786
* https://github.com/telefonicaid/fiware-orion/issues/3787
* https://github.com/telefonicaid/fiware-orion/issues/3789

**Comment by fgalan** [comment]
Local test execution works. The fails in GitActions is probably due to some kind of problem in the CI image. I'm on it.

**Comment by fgalan** [comment]
At commit d756e6a18ca0ced3d21db5350c191a018d854052, leak test pass is ok:

```
6 functional tests failed (not a leak, just a func-test failure):
   028: https.test (exit code 11)
   352: attribute_dates.test (exit code 1)
   355: filter_attr_datecreated_sub.test (exit code 1)
   356: filter_attr_datemodified_sub.test (exit code 1)
   362: filter_datecreated_sub.test (exit code 1)
   516: sub_from_active_to_fail.test (exit code 1)
---------------------------------------

Total test time: 17651.25 seconds (294 minutes)
Great, all valgrind tests ran without any memory leakage
```

**Comment by fgalan** [comment]
> Local test execution works. The fails in GitActions is probably due to some kind of problem in the CI image. I'm on it.

The fail was due to lack of cmake version 3 in the CI image, which is not installed by default in CentOS 7 (the base OS for the CI image). Probably I could have solved in "CentOS7 space" but in an ugly way, so I prefer to move to CI to CentOS 8  (where cmake version 3 is the native one).

I found some problems in the process and it took more than expected. The good news is that by the same price now we run Orion is a newer operations system version :)

This is the delta of changes to accomplish this: https://github.com/telefonicaid/fiware-orion/compare/d756e6a...bc58e55. Note no changes in the code took place, so the leak pass reported above is still valid (except some changes in unit test code, whith doesn't have any impact).

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
