### PR TITLE
fix invalid date in query parameter with GET entities API

### PR DESCRIPTION
**Pull request by ArqamFarooqui110719**
fix invalid date in query parameter with GET entities API (Issue #1995 )

### CODE REVIEW

**Comment by fgalan** [comment]
A lot (amost all?) tests are failing with thes PR.

@ArqamFarooqui110719 could you have a look and identify the cause, please?

**Comment by ArqamFarooqui110719** [comment]
Yes I'm looking into the issue.

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan  
As per my investigation, when we are requesting the below GET API:
```
curl -X GET 'localhost:1026/v2/entities?q=mytime<=2016-04-05T14:10:4XX.00Z'
```
It is following below code flow and returning error after (PR #4623 ).
 
Orion_GET_API_Flow

But the other APIs such as POST subscription (FT #4120), GET APIs with query parameter as string (FT #1156) is also calling the same functions for parsing the query parameter, but I don't think that is a correct way to parse a normal string within `parse8601Time()` function.
 
Create Subscription API which causing the issue is:
```
curl -iX POST '
[http://localhost:1026/v2/subscriptions'](http://localhost:1026/v2/subscriptions%27)
-H 'Content-Type: application/json' -d '
{
  "subject": {
    "entities": [
      {
        "id": "E1",
        "type": "T"
      }
    ],
    "condition": {
      "expression": {
        "q": "A:foo,null"
      }
    }
  },
  "notification": {
    "http": {
      "url": "
[http://127.0.0.1:1028/accumulate"](http://127.0.0.1:1028/accumulate%22)
    }
  }
}'
```
Above API is causing issue due to query parameter (q) in `condition` part. In`q = A:foo,null`, A is not a valid character for DateTime, so parse8601Time() function is returning `-1 or error` due to which the FT (#4210) is getting failed.

GET entities API (FT #1156) which causing the issue is:
```
curl -X GET
[http://localhost:1026/v2/entities?mq=t.'a'.'b.c.d'>=string](http://localhost:1026/v2/entities?mq=t.%27a%27.%27b.c.d%27%3E=string)
```

In this case also, query parameter is parsing in `parse8601Time()` function, so same code flow and same error.

Please provide your opinion and guidance on this situation, what should I do?

**Comment by fgalan** [comment]
The problem here is that you cannot assume any that `q` attribute has an special semantic.

Consider the following example. You have two entities, using the same attribute name but different types, eg:

Entity1 with:

```
"A": {
  "value": "foo",
  "type": "Text"
}
```

Entity2 with:


```
"A": {
  "value": "2024-01-01T00:00:00Z",
  "type": "DateTime"
}
```

so you can do a query like this `GET /v2/entities?q=A:foo`. That query would return Entity1.

Maybe https://github.com/telefonicaid/fiware-orion/issues/1995 is pointless and should be closed? My point is that we cannot do any attributetype-based validation at `q` (DateTime or any other) as I argue above.

@ArqamFarooqui110719 what do you think?

**Comment by ArqamFarooqui110719** [comment]
> The problem here is that you cannot assume any that `q` attribute has an special semantic.
> 

Yes I also have same understanding.

> 
> Maybe #1995 is pointless and should be closed? My point is that we cannot do any attributetype-based validation at `q` (DateTime or any other) as I argue above.
> 
> @ArqamFarooqui110719 what do you think?

But I feel that the `parseTime8601()` function should not parse the normal string and it should only be used for parsing the DateTime values. And there should be a separate function for parsing the normal strings for example: `parseStringValues()`. 
**By doing so, we can correctly parse the date values as well as string values separately without any issue.**

To achieve that we can follow below steps:
1. before calling the parsing function (parseTime8601()` directly, first we need to check whether the given string is a datetime or normal string using regex. For this we can create a separate function like `isDateTime()`. 
2. if the attribute value is `DateTime` then call the `parsetime8601()` function for remaining parsing of DateTime attribute.
3. if the attribute value is not DateTime (Normal string), Then we should call the normal string parsing function. 
(In normal string case, I think we only need to check for forbidden characters)

Please find below screenshot for above implementation:
Orion_GET_API_Fix_1995


Using the above method we can separate the parsing logic as well as we can restrict the usage of invalid characters in query parameter.

@fgalan What is your opinion on this?

**Comment by fgalan** [comment]
Not sure if I'm getting your point...

> But I think that the `parseTime8601()` function should not parse the normal string and it should only be used for parsing the DateTime values

Based in my [example above](https://github.com/telefonicaid/fiware-orion/pull/4623#issuecomment-2407527901), in case for instance of `GET /v2/entities?q=A:foo`, how do you now that `foo` should be interpreted as normal string or as date representation?

For Entity1, `foo` is valid as normal string (because `A` attribute type in Entity1 is not DateTime)

For Entity2, `foo` should be interpreted as a date (because `A` attribute type in Entity2 is DateTime)

Ok, you could inspect attributes and check the type in each one (so you could have a "parse ok" or "parse nok" for each entity),  but, which would be the purpose? How would be used these checks in the response to  `GET /v2/entities?q=A:foo`?

Note it is not an error from user standpoint to ask for `A:foo` without worrying about the attribute type in actual entities. The user just want to get entities which `A` attribute is the string `foo` and it's ok for him not getting in the response other entities (such the ones using DateTimes for `A`).

I hope have clarifying my point...

**Comment by ArqamFarooqui110719** [comment]
> 
> Based in my [example above](https://github.com/telefonicaid/fiware-orion/pull/4623#issuecomment-2407527901), in case for instance of `GET /v2/entities?q=A:foo`, how do you now that `foo` should be interpreted as normal string or as date representation?
> 
> For Entity1, `foo` is valid as normal string (because `A` attribute type in Entity1 is not DateTime)
> 
> For Entity2, `foo` should be interpreted as a date (because `A` attribute type in Entity2 is DateTime)
> 
> Ok, you could inspect attributes and check the type in each one (so you could have a "parse ok" or "parse nok" for each entity), but, which would be the purpose? How would be used these checks in the response to `GET /v2/entities?q=A:foo`?
> 
> Note it is not an error from user standpoint to ask for `A:foo` without worrying about the attribute type in actual entities. The user just want to get entities which `A` attribute is the string `foo` and it's ok for him not getting in the response other entities (such the ones using DateTimes for `A`).
> 
Yes I understood the above point.

But in my [last comment](https://github.com/telefonicaid/fiware-orion/pull/4623#issuecomment-2429371778), I meant that-
 inspecting the attribute value using regex not attribute type in `isDateTime()` function (may be something like following):
```
bool isDateTime(const std::string& ss)
{
  std::regex dateTimePattern(R"(^\d{4}-\d{2}-\d{2}([T ]\d{2}:\d{2}:\d{2}(\.\d{3})?(Z)?)?$)");
  return std::regex_match(ss, dateTimePattern);
}
```
The example given in last comment regarding entity1 and entity2, In that case, this function will treat `foo` as a normal string value and only datetime formatted string will treated as datetime value.

The above function (`isDateTime()`) will match the DateTime patterns like `YYYY-MM-DD`, `YYYY-MM-DDTHH:MM:SS` and `YYYY-MM-DDTHH:MM:SS.sssZ` etc. And the `foo` (or any other string value) will be treated as normal string.


(I think it can work! Although I need to test it for all use cases.)

**Comment by fgalan** [comment]
Maybe you could add to the PR a .test covering your use cases (including the different possibilities)? Maybe that way I can get a clearer understanding of your idea from a API user perspective.

**Comment by ArqamFarooqui110719** [comment]
Hi @fgalan 
I have investigated on the approach shared in the [above comment](https://github.com/telefonicaid/fiware-orion/pull/4623#issuecomment-2431617608).
My approach was to segregate the parsing logic for normal string parameters and DateTime type values. But in this case it seems very lengthy to findout all possible pattern for datetime value (valid and invalid) based on which we can segregate the normal strings.
I have investigated and tried my best but it seems it will be almost impossible to completely fix the issue. So I think we can close the Issue and PR.

**Comment by fgalan** [comment]
> So I think we can close the Issue and PR.

I agree.

Thanks for the investigation!

**Pull request closed without merging**
