### PR TITLE
Valgrind regression for 3.11.0 + fixes

### PR DESCRIPTION
**Pull request by fgalan**
This PR will be closed without merge after use.

Similar to PR https://github.com/telefonicaid/fiware-orion/pull/4370

### CODE REVIEW

**Comment by fgalan** [comment]
The only test that fails seems to be a glitch, as local execution works fine:

```
(p3) fermin@bodoque:~/src/fiware-orion/test/valgrind$ ./valgrindTestSuite.sh filtering_out_all_metadata_sub.test 
vie 26 ene 2024 10:26:23 CET
Run tests 0 to 0
./valgrindTestSuite.sh: línea 243: cd: test/valgrind: No existe el fichero o el directorio
Test 001/1: 3290_filtering_out_all_metadata_sub/filtering_out_all_metadata_sub ...................................................................... OK (13.13 seconds)
Total test time: 13.18 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```

Rerunning tests...

**Comment by fgalan** [comment]
> Rerunning tests...

It has failed same test in the second attemp

```
 1 test cases show valgrind errors:
  849: filtering_out_all_metadata_sub shows 4 valgrind errors
```

I have also checked with the CI image and it works:

```
docker run --network host --rm -e CB_NO_CACHE=ON -e FT_FROM_IX=849 -e FT_TO_IX=849 -v $(pwd):/opt/fiware-orion telefonicaiot/fiware-orion:ci build -miqts valgrind

...
===================================== VALGRIND TESTS =================================
Builder: fix makefile
Fri Jan 26 11:14:57 UTC 2024
Run tests 849 to 849
Test 849/1174: 3290_filtering_out_all_metadata_sub/filtering_out_all_metadata_sub ................................................................... OK (39.77 seconds) (no leak but ftest error 1)


1 functional tests failed (not a leak, just a func-test failure):
   849: filtering_out_all_metadata_sub.test (exit code 1)
```

Running test third time...

**Comment by fgalan** [comment]
Another run with CI image with the failing test and some previous ones:

```
docker run --network host --rm -e FT_FROM_IX=844 -e FT_TO_IX=849 -v $(pwd):/opt/fiware-orion telefonicaiot/fiware-orion:ci build -miqts valgrind
...
===================================== VALGRIND TESTS =================================
Builder: fix makefile
Fri Jan 26 11:27:42 UTC 2024
Run tests 844 to 849
Test 844/1174: 3272_custom_notification_sending_0-length_request/null_payload_update ................................................................ OK (40.76 seconds) (no leak but ftest error 1)
Test 845/1174: 3280_right_processing_of_json_special_chars/right_processing_of_json_special_chars ................................................... OK (6.31 seconds)
Test 846/1174: 3282_compound_not_render_in_not_matching_registration/compound_not_render_in_not_matching_registration ............................... OK (6.86 seconds)
Test 847/1174: 3285_csub_isolation/csub_isolation_attrs_filter ...................................................................................... OK (9.70 seconds)
Test 848/1174: 3285_csub_isolation/csub_isolation_metadata_filter ................................................................................... OK (9.77 seconds)
Test 849/1174: 3290_filtering_out_all_metadata_sub/filtering_out_all_metadata_sub ................................................................... OK (12.67 seconds)


1 functional tests failed (not a leak, just a func-test failure):
   844: null_payload_update.test (exit code 1)
---------------------------------------
```

**Comment by fgalan** [comment]
In github Attemp number 3:

```
2 test cases show valgrind errors:
  655: long_service_names_in_subscriptions shows 4 valgrind errors
  849: filtering_out_all_metadata_sub shows 4 valgrind errors
---------------------------------------
```

**Comment by fgalan** [comment]
In github attemp 4:

```
3 test cases show valgrind errors:
  655: long_service_names_in_subscriptions shows 4 valgrind errors
  803: more_than_1000_types shows 31 valgrind errors
  849: filtering_out_all_metadata_sub shows 4 valgrind errors
---------------------------------------
```

This is getting weird :)

**Comment by fgalan** [comment]
Attemp 5 finally worked. That shows the fail was a glitch.

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
