### PR TITLE
Fix for PATCH update operation when 'multiple SP' or 'SP with wildcard #' is used.

### PR DESCRIPTION
**Pull request by ArqumFarooqui-NEC**
Fix Issue #3640 for PATCH update operation when 'multiple ServicePath' or 'ServicePath with wildcard #' is used.

### CODE REVIEW

**Comment by fgalan** [comment]
It would be great if you could include in the PR functional tests (i.e. .test files) to cover the behaviours described in the original issue (see https://github.com/telefonicaid/fiware-orion/issues/3640#issuecomment-802088165)

**Comment by ArqumFarooqui-NEC** [comment]
> It would be great if you could include in the PR functional tests (i.e. .test files) to cover the behaviours described in the original issue (see [#3640 (comment)](https://github.com/telefonicaid/fiware-orion/issues/3640#issuecomment-802088165))


Hi @fgalan sir, I'm working on the functional test cases, I'll add it soon.
Thank you:)

**Comment by ArqumFarooqui-NEC** [comment]
Hi @fgalan sir,
I've added functional test cases. Kindly review it, If it is okay, then please merge this PR.
Thank you:)

**Comment by fgalan** [comment]
Thanks for your work on this PR!

The .test looks great and I think covers the following cases pretty well:

> PATCH with servicepath #, it should return 400.
> PATCH with multiple servicepath, it should return 400.

However, it would be great if you could add a step 09 and 10 to cover also this one:

> PATCH without servicepath and if entity doesn't exist, returning 404

Something like this may help:

```
echo "09. Attempt to UPDATE entity E2 with A2=22, using PATCH v2/update operation, without specifiying service path, see 404 error"
echo "============================================================================================================================"
payload='{
    {
      "A2": {
        "value": 22
      }
    }
}'
orionCurl --url '/v2/entities/E2/attrs?type=T2' -X PATCH --payload "$payload"
echo
echo


echo "10. Attempt to UPDATE entity E2 with A2=22, using PATCH v2/update operation, with servicepath '/Level_1/, see 404 error"
echo "======================================================================================================================="
payload='{
    {
      "A2": {
        "value": 22
      }
    }
}'
orionCurl --url '/v2/entities/E2/attrs?type=T2' -X PATCH --payload "$payload" --header "Fiware-ServicePath:/Level_1/"
echo
echo
```

In addition, please add to CHANGES_NEXT_RELEASE an entry about the fix of this PR. Suggested line:

```
- Fix: PATCH update operation right error codes when multiple service paths or service path /# is used (#3812)
```

**Comment by ArqumFarooqui-NEC** [comment]
> However, it would be great if you could add a step 09 and 10 to cover also this one:
> > PATCH without servicepath and if entity doesn't exist, returning 404

Hi @fgalan sir, Thanks for your suggestion:) 
I've added the mentioned test case (i.e 09 and 10) and updated the CHANGES_NEXT_RELEASE file & test file. 
Kindly review it, If it is okay, then please merge this PR.
Thank you:)

**Review by fgalan — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
