### PR TITLE
FIX Improve notification pool worker thread termination logic

### PR DESCRIPTION
**Pull request by fgalan**
Issue #3877

- [x] Test under queue saturation situations

### CODE REVIEW

**Comment by fgalan** [comment]
Example of termination trace:

```
time=2021-06-11T08:38:59.689Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[258]:shutdownClient | msg=shutdown mongo client
time=2021-06-11T08:38:59.689Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #0
time=2021-06-11T08:38:59.689Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #1
time=2021-06-11T08:38:59.690Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #2
time=2021-06-11T08:38:59.690Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #3
time=2021-06-11T08:38:59.690Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #4
time=2021-06-11T08:38:59.691Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #5
time=2021-06-11T08:38:59.692Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #6
time=2021-06-11T08:38:59.692Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #7
time=2021-06-11T08:38:59.692Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #8
time=2021-06-11T08:38:59.693Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #9
time=2021-06-11T08:38:59.694Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 117fa700 receiving termination signal...
time=2021-06-11T08:38:59.694Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 137fe700 receiving termination signal...
time=2021-06-11T08:38:59.694Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 13fff700 receiving termination signal...
time=2021-06-11T08:38:59.694Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 11ffb700 receiving termination signal...
time=2021-06-11T08:38:59.694Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread ebfff700 receiving termination signal...
time=2021-06-11T08:38:59.694Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 22510700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 21d0f700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread ea7fc700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 22d11700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 10ff9700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 2150e700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread eaffd700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 20d0d700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread eb7fe700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread e97fa700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread e9ffb700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread e8ff9700 receiving termination signal...
time=2021-06-11T08:38:59.695Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread dbfff700 receiving termination signal...
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 12ffd700 receiving termination signal...
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[134]:workerFunc | msg=Thread 127fc700 receiving termination signal...
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 22d11700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 22510700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 21d0f700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 2150e700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 20d0d700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 13fff700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 137fe700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 12ffd700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 127fc700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 11ffb700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 117fa700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread 10ff9700 joined
time=2021-06-11T08:38:59.696Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread ebfff700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread eb7fe700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread eaffd700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread ea7fc700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread e9ffb700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread e97fa700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread e8ff9700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[99]:stop | msg=Thread dbfff700 joined
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=Notifier.cpp[57]:~Notifier | msg=Notifier destructor is not implemented
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[580]:exitFunc | msg=try-taking req semaphore
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[582]:exitFunc | msg=calling subCacheDestroy
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=subCache.cpp[583]:subCacheDestroy | msg=destroying subscription cache
time=2021-06-11T08:38:59.697Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[588]:exitFunc | msg=error removing PID file '/tmp/orion_9999.pid': No such file or directory
time=2021-06-11T08:38:59.697Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[591]:exitFunc | msg=Orion shutdown completed
```

Note there are 20 "Thread X receiving termination signal" traces (as we start with `-notificationMode threadpool:200:20`), each one which its corresponding "Thread X joined" trace.

**Comment by fgalan** [comment]
As expected, the current implementation doesn't work when the queue is full. For instance, if we run test case cases/3843_per_service_notif_queue/default_service_notif_queue.test with the following modification so it doesn't stop processes when finishes:

```diff
diff --git a/test/functionalTest/cases/3843_per_service_notif_queue/default_service_notif_queue.test b/test/functionalTest/cases/3843_per_service_notif_queue/default_service_notif_queue.test
index f0ee2ff1b..5a32d9e1b 100644
--- a/test/functionalTest/cases/3843_per_service_notif_queue/default_service_notif_queue.test
+++ b/test/functionalTest/cases/3843_per_service_notif_queue/default_service_notif_queue.test
@@ -27,7 +27,7 @@ Per service notification queues (regression case)
 dbInit ${CB_DB_NAME} serv1
 dbInit ${CB_DB_NAME} serv2
 dbInit ${CB_DB_NAME} serv3
-brokerStart CB 0 IPv4 -multiservice -notificationMode threadpool:3:2
+brokerStart CB 0-255 IPv4 -multiservice -notificationMode threadpool:3:2 -httpTimeout 100000
 accumulatorStart --pretty-print localhost $LISTENER_PORT
 
 --SHELL--
@@ -166,7 +166,7 @@ echo
 # It is not usual to stop accumulator in the SHELL section, but this way we
 # ensure all connections are terminated so upon stopping of Context Broker
 # no memory is lost and no false positive is reported by valgrind pass
-accumulatorStop $LISTENER_PORT
+#accumulatorStop $LISTENER_PORT
 
 
 --REGEXPECT--
@@ -236,7 +236,7 @@ Date: REGEX(.*)
 
 
 --TEARDOWN--
-brokerStop CB
-dbDrop ${CB_DB_NAME} serv1
-dbDrop ${CB_DB_NAME} serv2
-dbDrop ${CB_DB_NAME} serv3
+#brokerStop CB
+#dbDrop ${CB_DB_NAME} serv1
+#dbDrop ${CB_DB_NAME} serv2
+#dbDrop ${CB_DB_NAME} serv3
```

Then I send SIGINT to CB (i.e `kill <cb pid>`) and I get:

```
time=2021-06-11T09:26:42.084Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[258]:shutdownClient | msg=shutdown mongo client
time=2021-06-11T09:26:42.084Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #0
time=2021-06-11T09:26:42.084Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #1
time=2021-06-11T09:26:42.084Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #2
time=2021-06-11T09:26:42.085Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #3
time=2021-06-11T09:26:42.085Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #4
time=2021-06-11T09:26:42.086Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #5
time=2021-06-11T09:26:42.086Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #6
time=2021-06-11T09:26:42.086Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #7
time=2021-06-11T09:26:42.086Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #8
time=2021-06-11T09:26:42.087Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #9
time=2021-06-11T09:26:42.089Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[94]:stop | msg=Runtime Error (thread kill message cannot be sent due to push in queue failed)
time=2021-06-11T09:26:42.089Z | lvl=ERROR | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[94]:stop | msg=Runtime Error (thread kill message cannot be sent due to push in queue failed)
```

and no matter if I stop the accumulator-server.py process (to close the connections so threads can not pop() from the queue again), the broker is stuck.

(If I send SIGINT again, CB process is stopped. It seems that functions registered with atexit() are called just one time, on the first SIGNIT. In the second SIGINT, the sigHandler() just ends with `exit(0)` and no function is called as response to that. Not fully sure about this, I have posted in SOF to clarify: https://stackoverflow.com/questions/67934725/are-atexit-registered-handlers-called-just-one-time)

**Comment by fgalan** [comment]
After cea0a9f89b87a082674963dc5f4a4dcfd60f84a4 now also works in saturation. The log now when I do the SIGINT signal is:

```
time=2021-06-11T09:49:20.728Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[258]:shutdownClient | msg=shutdown mongo client
time=2021-06-11T09:49:20.728Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #0
time=2021-06-11T09:49:20.729Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #1
time=2021-06-11T09:49:20.730Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #2
time=2021-06-11T09:49:20.730Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #3
time=2021-06-11T09:49:20.731Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #4
time=2021-06-11T09:49:20.731Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #5
time=2021-06-11T09:49:20.731Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #6
time=2021-06-11T09:49:20.732Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #7
time=2021-06-11T09:49:20.732Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #8
time=2021-06-11T09:49:20.732Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=mongoConnectionPool.cpp[269]:shutdownClient | msg=closing connection #9
```

Note that now the "Runtime Error (thread kill message cannot be sent due to push in queue failed)" trace doesn't appear.

Now if we kill the accumulator-server.py process (in real situations, when the HTTP timeout expires) the threads will take next elements in the queue (the kill messages) and terminate. 

```
time=2021-06-11T09:49:45.383Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[137]:workerFunc | msg=Thread 3513700 receiving termination signal...
op=QueueWorkers.cpp[137]:workerFunc | msg=Thread 2d12700 receiving termination signal...
time=2021-06-11T09:49:45.383Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[102]:stop | msg=Thread 3513700 joined
time=2021-06-11T09:49:45.383Z | lvl=DEBUG | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=QueueWorkers.cpp[102]:stop | msg=Thread 2d12700 joined
time=2021-06-11T09:49:45.384Z | lvl=INFO | corr=N/A | trans=N/A | from=N/A | srv=N/A | subsrv=N/A | comp=Orion | op=contextBroker.cpp[591]:exitFunc | msg=Orion shutdown completed
```

and the process is effectively stopped.

**Review by mapedraza — APPROVED** [review]
LGTM

**Pull request merged**
