### PR TITLE
actionType delete additional testCases

### PR DESCRIPTION
**Pull request by fgalan**

### CODE REVIEW

**Review by pelayogb — APPROVED** [review]
LGTM

**Review by pelayogb — APPROVED** [review]

**Review by pelayogb — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does a small modification to the documentation. It would be great if you could sync in the Japanese translation, please. Thanks in advance!

**Comment by fisuda** [comment]
I sent the PR #4446. Thanks.

**Pull request merged**
