### PR TITLE
support for Mongo 3.4 with authentication

### PR DESCRIPTION
**Pull request by mathi123**

### CODE REVIEW

**Comment by fgalan** [comment]
I understand this PR was a first attemp, overpassed by #3245 and therefore closed. Is that correct?

**Comment by mathi123** [comment]
Indeed, I created 2 PR because github did not seem to pick up any new commits on the branch. Very strange.. Did you do anything to trigger the build this morning?

**Comment by fgalan** [comment]
> Did you do anything to trigger the build this morning?

You mean the build of the docker container at https://hub.docker.com/r/fiware/orion ?

**Comment by mathi123** [comment]
No, the last travis build in #3245.

**Pull request closed without merging**
