### PR TITLE
FIX remove NGSIv1 lasting API ops

### PR DESCRIPTION
**Pull request by fgalan**
Test are expected to fail in the first pass of this PR.

- [x] fix/disable tests
- [x] modify deprecation documentation

### CODE REVIEW

**Review by mapedraza — COMMENTED** [review]
Should the following test deleted?
- test/functionalTest/cases/0968_ngsi10_asterisk_subs/0968_ngsi10_asterisk_subs.test.DISABLED
- telefonicaid/fiware-orion/test/functionalTest/cases/0585_empty_type_in_response/ngsi10.test.DISABLED
- telefonicaid/fiware-orion/test/functionalTest/cases/0968_ngsi10_asterisk_subs/0968_ngsi10_asterisk_subs.test.DISABLED

**Comment by fgalan** [comment]
>  test/functionalTest/cases/0968_ngsi10_asterisk_subs/0968_ngsi10_asterisk_subs.test.DISABLED

The idea of the test is still validad, but moved to NGSIv2. Done in commit f755865c4

>  telefonicaid/fiware-orion/test/functionalTest/cases/0585_empty_type_in_response/ngsi10.test.DISABLED
>  telefonicaid/fiware-orion/test/functionalTest/cases/0968_ngsi10_asterisk_subs/0968_ngsi10_asterisk_subs.test.DISABLED

Both removed (they are a regression tests for a fail in NGSIv1 pure API, so they make no sense in NGSIv2)

> telefonicaid/fiware-orion/test/functionalTest/cases/0585_empty_type_in_response/ngsi9.test.DISABLED

I think this is the same of the first case, istn't it?

**Review by mapedraza — APPROVED** [review]
LGTM

**Comment by fgalan** [comment]
@fisuda this PR does some modifications to English .md files. It would be great if you could sync the Japanese translation, please. Thanks in advance!

**Comment by fisuda** [comment]
I sent the PR #4572.
Thanks.

**Pull request merged**
