### PR TITLE
REMOVE casub functionality

### PR DESCRIPTION
**Pull request by fgalan**

### CODE REVIEW

**Comment by fgalan** [comment]
@fisuda this PR is almost ready but involves modifications in the .md documentation.

I did the modifications in the English version of the documentation and also some modifications in the Japanese devel manual, that I hope may help. However, given I don't know Japanese I could have made mistakes...

Thus, would you be so kind of complete the synchronization of the Japanese documentation (fixing any possible error I could have made in my partial modifications), please? I'd suggest to do it as PR into this one (#3571) instead of that into master (thus I can merge your PR on remove/casubs branch).

Thanks!

**Comment by fisuda** [comment]
@fgalan, 

I understand. I will send my PR to this PR.

Thank you.

**Comment by fgalan** [comment]
@fisuda I did a little adjustment to documentation in commit https://github.com/telefonicaid/fiware-orion/pull/3571/commits/1d7f3f35f325115e65b3a599d40969b37d0b10c2. It would be great if you could do a PR to this PR in order to sync the Japanese translation, please.

Sorry for the inconvenience.

**Comment by fisuda** [comment]
I sent PR #3762.  Please review it.

**Comment by fgalan** [comment]
@fisuda some extra adjustments to doc were done in commit b23d80e21. I hope this time being the last ones before merging.

Could you sync the Japanese translation with a PR to this PR, please? Thanks!

Sorry for the inconveniences

**Comment by fisuda** [comment]
I have just sent PR #3763. Please review it.

**Review by AlvaroVega — APPROVED** [review]
LGTM

**Pull request merged**
