### PR TITLE
ADD geo:proximity orderBy

### PR DESCRIPTION
**Pull request by fgalan**
@kzangeli 
@crbrox 
@jmcanterafonseca (nice to have)

### CODE REVIEW

**Comment by crbrox** [comment]
LGTM

**Comment by kzangeli** [comment]
LGTM

**Comment by jmcanterafonseca** [comment]
sorry for arriving late here but I think it would be better to name the pseudo-property 'geo:distance' instead proximity, I think it is shorter and clearer. 

thanks

**Comment by jmcanterafonseca** [comment]
better geo:distance

2016-02-23 10:21 GMT+01:00 Ken Zangelin <notifications@github.com>:

**Comment by fgalan** [comment]
`geo:distance` sounds better than `geo:proximity`. We will do an overarall change in code + test + doc before releasing 0.28.0. Thanks!

**Comment by fgalan** [comment]
PR implementing the rename: https://github.com/telefonicaid/fiware-orion/pull/1842

**Pull request merged**
