### PR TITLE
Fix Non-Primitive Values from a Registered Content Provider are not showing a value

### PR DESCRIPTION
**Pull request by fgalan**
This PR is a kind of continuation of PR https://github.com/telefonicaid/fiware-orion/pull/3379 and completes the solution for issue #3162 

Remember we have already a solution in place in branch https://github.com/telefonicaid/fiware-orion/tree/bugfixing/3162_fix_but_potential_leak but we suspect about memory leaks on it. This PR provides the same fix but (suppossely) without introducing any leak.

In fact, I have downloaded the .test in that branch and included them in this one in order to ensure the fix is equivalent from a functional point of view, in particular:

* blanked_out_attr.test
* registration_without_provider.test
* query_for_arrays.test (This is special. We already have a query_for_arrays.test.DISABLED file in master branch which seems to be an early and not fully working version of the one in bugfixing/3162_fix_but_potential_leak. I understand that @kzangeli took initially query_for_arrays.test.DISABLED and ajusted it after developing the fix. I have used the version on the bugfixing/3162_fix_but_potential_leak branch, the diff in this PR shows changes that I understand are ok)

(Curiously, branch bugfixing/3162_fix_but_potential_leak also includes a federation_problem.test.DISABLED test, but it is not related with forwarded queries. The .test is valuable related with federation features and I plan to reuse it, but not in this PR)

A valgrind test pass is yet pending before merging to ensure this PR doesn't introduce any leak but in the meanwhile it would be great if @kzangeli could have a look (if you can/want, of course ;)

### CODE REVIEW

**Comment by fgalan** [comment]
Valgrind execution result:

```
2 test cases show valgrind errors:
  631: subCacheThrottlingAndExpirationAfterRefresh shows 80 valgrind errors
  825: 2064_attrs_blacklist_complex shows 32 valgrind errors
---------------------------------------



4 functional tests failed (not a leak, just a func-test failure):
   335: query_local_query_not_found.test (exit code 1)
   383: attribute_dates.test (exit code 1)
   396: get_entity_dates.test (exit code 1)
   945: 2750_reset_metrics.test (exit code 1)
---------------------------------------

Total test time: 16434.76 seconds (273 minutes)
Great, all valgrind tests ran without any memory leakage
makefile:393: recipe for target 'valgrind' failed

$ contextBroker --version | head -n 1
2.0.0-next (git version: 790231aa9787dd60aa8ad9921068c9e017baaa6f)
```

I have run individually the two ones failing to ensure they are glitches:

```
$ test/valgrind/valgrindTestSuite.sh subCacheThrottlingAndExpirationAfterRefresh.test
vie dic 14 09:48:49 CET 2018
Test 001/1: 1308_subscription_cache/subCacheThrottlingAndExpirationAfterRefresh ..................................................................... OK (39.30 seconds)
Total test time: 39.47 seconds (0 minutes)
Great, all valgrind tests ran without any memory leakage
```

```
$ test/valgrind/valgrindTestSuite.sh 2064_attrs_blacklist_complex.test
vie dic 14 09:51:41 CET 2018
Test 001/1: 2064_attrs_blacklist_subs/2064_attrs_blacklist_complex .................................................................................. OK (65.39 seconds)
Total test time: 65.56 seconds (1 minutes)
Great, all valgrind tests ran without any memory leakage
```

In sum: everything ok.

**Comment by fgalan** [comment]
Issue #3282 seems to be also solved. A .test to cover it has been added to the PR.

**Comment by fgalan** [comment]
Please @fisuda take into account the removal of a paragraph in the documentation, to be synched in Japanese translation if needed.

**Comment by fisuda** [comment]
@fgalan Well noted with thank you.

**Pull request merged**
