### PR TITLE
Rework Orion Documentation

### PR DESCRIPTION
**Pull request by mapedraza**
The purpose of this PR is to implement the changes needed to improve Orion's documentation. 

Taks to perform

- [x] Create a new `orion-api.md` file, based on apiary file (first commit on feature/doc-rework, without associated sub-PR)
- [x] Improve and modify the structure https://github.com/telefonicaid/fiware-orion/pull/4142
- [x] Refactor *query* parameters list into tables #4150
- [x] Refactor *url* parameters list into tables https://github.com/telefonicaid/fiware-orion/pull/4155
- [x] Reorder operations sections + some capitalization and rendering fixes https://github.com/telefonicaid/fiware-orion/pull/4156 
- [x] Subscription payload into tables https://github.com/telefonicaid/fiware-orion/pull/4158
- [x] Include `orion-api.md` into RTD https://github.com/telefonicaid/fiware-orion/pull/4160
- [x] Add links between sections https://github.com/telefonicaid/fiware-orion/pull/4165
- [x] Review all the request sections (except batch operations) https://github.com/telefonicaid/fiware-orion/pull/4167
- [x] Review batch operations https://github.com/telefonicaid/fiware-orion/pull/4173
- [x] Fix links between sections https://github.com/telefonicaid/fiware-orion/pull/4174

*Up to this point, no new content has been added with regards to the original NGSIv2 spec document. The next PRs will start adding/removing content, consolidating documentation in other .md files*

- [x] Add to `orion-api.md` the topics included in implementation notes documentation (several sub-PRs, detail in [below comment](https://github.com/telefonicaid/fiware-orion/pull/4141#issuecomment-1184127833))
    - [x] PR1 - Modify tables https://github.com/telefonicaid/fiware-orion/pull/4176
    - [x] PR2 - Encrich sections (direct mapping) https://github.com/telefonicaid/fiware-orion/pull/4181
    - [x] PR3 - New sections https://github.com/telefonicaid/fiware-orion/pull/4182
    - [x] PR4 - "Differences regarding the  original NGSIv2 spec" Section #4183
    - [x] PR5 - Other changes https://github.com/telefonicaid/fiware-orion/pull/4185
- [x] Fix wrong update operator examples https://github.com/telefonicaid/fiware-orion/pull/4187
- [x] Fix [issue #4178](https://github.com/telefonicaid/fiware-orion/issues/4178) https://github.com/telefonicaid/fiware-orion/pull/4188
- [x] Review `GET /v2/types` and `GET /v2/types/{type}` sections (some flaws exists) https://github.com/telefonicaid/fiware-orion/pull/4189
- [x] Some reviews on orion-api.md https://github.com/telefonicaid/fiware-orion/pull/4191
   - [x] New section "Notification triggering" with the current content in the subscription datamodel (including a link from that point)
   - [x] regarding dateExpires, fix "How the server controls entity expiration is an implementation specific aspect"
   - [x] Check "neutral statement" (e.g. "NGSIv2 server", "implementation", etc.)
   - [x] Review subscription payloads examples that include status with failed value
- [x] Integrate content from multitenancy.md and service_path.md https://github.com/telefonicaid/fiware-orion/pull/4192 
- [x] Remove `GET /v2` operation and mark it as deprecated for next version https://github.com/telefonicaid/fiware-orion/pull/4194
- [x] Cleanup fixes https://github.com/telefonicaid/fiware-orion/pull/4196
   - [x] Look in the whole documentation (and code, and test, etc.) for references to deleted md files and fix them, change the links to the proper section in the new orion-api.md document
   - [x] No direct reference to NGSIv2 spec should remain in the documentation (the reference in the Orion API preface should suffice). Existing references to NGSIv2 spec should be replaced to references to Orion API (hint: text search for "github.io")
   - [x] Remove structured_attribute_valued.md (already covered by "JSON Attribute Representation" section)
   - [x] Remove update_action_types.md (already covered by "POST /v2/op/update" section)
   - [x] Remove geolocation.md (the document is basically just a pointer, with no content)
   - [x] Move GeoJson limitations from "Geospatial properties of entities" to specific "GeoJSON" subsection
   - [x] Remove filtering.md (the document is basically just a set of pointers, with no content)
   - [x] Integrate pagiantion.md into new section "Pagination"
   - [x] Cite regex.md in the proper places (eg. when idPattern is mentioned, etc.)
- [x] Reorder orion-api.md sections based [in this list](https://github.com/telefonicaid/fiware-orion/pull/4141#issuecomment-1222017142) https://github.com/telefonicaid/fiware-orion/pull/4199
- [x] Some final? fixes https://github.com/telefonicaid/fiware-orion/pull/4200/
  - [x] Changes in the API route titles
  - [x] Sub-divide Custom Notification section (it was pretty large)
- [x] ~Proof-read~, preamble and fix links to NGSIv2 spec https://github.com/telefonicaid/fiware-orion/pull/4203
- [ ] (Not actually as part of feature/doc-rework PRs) review github.io pages to link to the new Orion API document https://github.com/telefonicaid/fiware-orion/pull/4197

This PR overpass https://github.com/telefonicaid/fiware-orion/pull/4140

### CODE REVIEW

**Comment by fgalan** [comment]
_Work in progress_

- Forbidden characters
- Update operators for attribute values
- Metadata update semantics
- Custom payload decoding on notifications
- Option to disable custom notifications
- Non-modifiable headers in custom notifications
- Header removal in custom notifications
- Limit to attributes for entity location
- Supported GeoJSON types in geo:json attributes
- Legacy attribute format in notifications
- Datetime support
- User attributes or metadata matching builtin name
- Subscription payload validations
- alterationType attribute
- actionType metadata
- ignoreType metadata
- noAttrDetail option
- Notification throttling
- Ordering between different attribute value types
- Oneshot subscriptions
- Subscriptions based in alteration type
- Custom notification extra macros
- Custom notification with JSON payload
- Custom notifications without payload
- MQTT notifications
- Notify only attributes that change
- Covered subscriptions
- timeout subscriptions option
- lastFailureReason and lastSuccessCode subscriptions fields
- failsCounter and maxFailsLimit subscriptions fields
- Ambiguous subscription status failed not used
- forcedUpdate option
- flowControl option
- Registrations
- skipForwarding option
- null support in DateTime and geolocation types
- keyValues not supported in POST /v2/op/notify
- Deprecated features

**Comment by mapedraza** [comment]
Some doubts regarding the following points:

1. Forbidden characters not present in Orion-api.md, you mean file? So, adding General restrictions from `forbidden_characters.md` and including into a new section on `Orion-api.md`, right?
3. Which wording is suggested?
4. should be moved as section, right?

**Comment by mapedraza** [comment]
The proposed strategy to include the content in this section is to make 5 bigger PRs with smaller sub PRs for each section:

* PR1 - Modify tables
3. Metadata update semantics
    - The `overrideMetadata` option must be included in the option tables in all operations supporting it (all updates, basically)
17. noAttrDetail option
    - To be included in the corresponding options tables
20. Oneshot subscriptions
    - Include new status "oneshot" in the corresponding table in the subscription datamodel
21. Subscriptions based in alteration type 
    - Include new field "alterationTypes" in the corresponding table in the subscription datamodel
25. MQTT notifications
    - Include the "mqtt" and "mqttCustom" fields within the subscriptions datamodel
    - With regards to mqttCustom, the section "Custom Notifcations" should be also modified
    - The mqtt_notifications.md makes sense as independent document (it will be linked from orion-api.md in the proper points)
26. Notify only attributes that change
    - Include "onlyChangedAttrs" field within the subscriptions datamodel
27. Covered subscriptions
    - Include "covered" field within the subscriptions datamodel
    - If the text is too long to be included in one table cell (most probably), then consider the option of describing it below the table (the same "trick" used to describe notification rules in subscription.subject.condition section)
28. timeout subscriptions option
    - Include "timeout" field within the subscriptions datamodel 
29. lastFailureReason and lastSuccessCode subscriptions fields
    - Include both fields within the subscriptions datamodel 
30. failsCounter and maxFailsLimit subscriptions fields
    - Include both fields within the subscriptions datamodel 
    - If the text is too long to be included in one table cell (most probably), then consider the option of describing it below the table (the same "trick" used to describe notification rules in subscription.subject.condition section)
32. forcedUpdate option
    - To be included in the corresponding options tables
33. flowControl option
    - To be included in the corresponding options tables
35. skipForwarding option
    - To be included in the corresponding options tables

* PR2-Encrich sections (direct mapping)
1. Forbidden characters
    - Maps to ~"Forbidden characters"~ "Field syntax restrictions" section in orion-api.md
    - This is a pointer to the actual content in "General restrictions" in forbidden_characters.md, which should be moved to orion-api.md.
3. Metadata update semantics
    - Modify the last bullet in "Partial Reprenstations" about metadata with the detail provided under "this sentence has two interpretations:"
4. Custom payload decoding on notifications
    - Maps to "Custom notification" section in orion-api.md
    - This is a pointer to the actual content in "Custom payload and headers special treatment" in forbidden_characters.md, which should be moved to orion-api.md.
5. Option to disable custom notifications
    - Maps to "Custom notification" section in orion-api.md
6. Non-modifiable headers in custom notifications
    - Maps to "Custom notification" section in orion-api.md
7. Header removal in custom notifications
    - Maps to "Custom notification" section in orion-api.md
8. Limit to attributes for entity location
    - In "Geospatial properties of entities" section, specify the limit is 1
    - The example showing the usage of ignoreType could be also be used here
9. Supported GeoJSON types in geo:json attributes
    - Maps to "Geospatial properties of entities" section in orion-api.md
10. Legacy attribute format in notifications
    - Maps to "attrsFormat" in the corresponding table in the subscription datamodel
14. alterationType attribute
    - Maps to "Build Attributes" section, with a new attribute
16. ignoreType metadata
    - Maps to "Metadata Attributes" section, with a new metadata
18. Notification throttling
    - Maps to "throttling" in the corresponding table in the subscription datamodel
    - If the text is too long to be included in one table cell, then consider the option of describing it below the table (the same "trick" used to describe notification rules in subscription.subject.condition section)
19. Ordering between different attribute value types
    - Maps to "Ordering Results" section in orion-api.md
22. Custom notification extra macros
    - Maps to "Custom Notifications" section in orion-api.md
23. Custom notification with JSON payload
    - Maps to "Custom Notifications" section in orion-api.md
24. Custom notifications without payload
    - Maps to "Custom Notifications" section in orion-api.md
36. null support in DateTime and geolocation types
    - Maps to "Special Attribute Types" and "Special Metadata Types" in orion-api.md

* PR3 - New sections
2. Update operators for attribute values
    - This probably deserves its own sub-section within "Specification" in orion-api.md, using the "normative" part (i.e. with a simpler introduction) of update_operators.md
    - The above subsection should be referred from sections describing attribute payloads: "JSON Entity Representation" and "JSON Attribute Representation"
    - What to do with the nice introduction in update_operations.md? I doesn't fit in a "nomative" document as orion-api.md is aimed to, but I wouldn't like to miss it...
3. Metadata update semantics
    - Probably a new sub-section within "Specification" in orion-api.md shoud be added, using the contents on "Updating metadata" section in metadata.md document
11. Datetime support
    - Maybe deserves a sub-section within "Specification" in the orion-api.md, with the same name ("Datetime support")
    - That section will be referred from DateTime bullet in "Special Attribute Types"
12. User attributes or metadata matching builtin name
    - Maybe deserves a sub-section within "Specification" in the orion-api.md, with the same name ("User attributes or metadata matching builtin name")
21. Subscriptions based in alteration type 
    - A new subsection under "Specification" should be create with the content of subscriptions_alttype.md document
20. Oneshot subscriptions
    - A new subsection under "Specification" should be create with the content of oneshot_subscription.md document

* PR4 - "Functionality in original NGSIv2 spec not yet covered" Section
15. actionType metadata
    - Maps to new section "Functionality in original NGSIv2 spec not yet covered" section (provisional name)
31. Ambiguous subscription status failed not used
    - Maps to new section "Differences regarding the  original NGSIv2 spec" section (provisional name)
    - status "failed" to be removed from the corresponding table in the subscription datadamodel
37. keyValues not supported in POST /v2/op/notify
    - To be mentioned in "Differences regarding the  original NGSIv2 spec" section (provisional name)
    - Option to be removed from corresponding options table
34. Registrations
    - The first bullet list maps to new section "Differences regarding the  original NGSIv2 spec" section (provisional name)
    - Removed from "Registration Operations" and the registrations datamodel what it is not currently supported
    - From "According to NGSIv2 specification..." maps to "Registration Operations" and the registrations datamodel

* PR5 - Other changes
3. Metadata update semantics
    - What about the rest of metadata.md document? Check that it is somehow covered in the current orion-api.md document. I think is is mostly covered, in negative case include it (maybe in "Context Metadata" subsection)
13. Subscription payload validations
    - The information in this section has been already captured by the "Optional" and "Type" columns in the subscription metadata
    - In addition, it is pretty much obsolete
    - Thus, it can be just removed
38. Deprecated features
     - Unsure. Maybe to be fully removed. Leave it for the last PR ;)

The idea behind the order of the PRs is to make the complex first (with the aim to merge them earlier)

Note that points 3, 20 and 21 are present in multiples PRs (but with different tasks)

**Comment by fgalan** [comment]
Sections will be reordered base in the following:

    - [Introduction](#introduction)
    - [Terminology](#terminology)
    - [MIME Types](#mime-types)
    - [JSON Entity Representation](#json-entity-representation)
    - [JSON Attribute Representation](#json-attribute-representation)
    - [Simplified Entity Representation](#simplified-entity-representation)
    - [Partial Representations](#partial-representations)
    - [General syntax restrictions](#general-syntax-restrictions)
    - [Identifiers syntax restrictions](#identifiers-syntax-restrictions)
    - [Error Responses](#error-responses)
    - [Multi tenancy](#multi-tenancy)
    - [Service path](#service-path)
    - [Special Attribute Types](#special-attribute-types)
    - [Builtin Attributes](#builtin-attributes)
    - [Special Metadata Types](#special-metadata-types)
    - [Builtin Metadata](#builtin-metadata)
    - [Attribute names restrictions](#attribute-names-restrictions)
    - [Metadata names restrictions](#metadata-names-restrictions)
    - [User attributes or metadata matching builtin name](#user-attributes-or-metadata-matching-builtin-name)
    - [Datetime support](#datetime-support)
    - [Geospatial properties of entities](#geospatial-properties-of-entities)
    - [Simple Query Language](#simple-query-language)
    - [Geographical Queries](#geographical-queries)
    - [Update operators for attribute values](#update-operators-for-attribute-values)
    - [Filtering out attributes and metadata](#filtering-out-attributes-and-metadata)
    - [Metadata update semantics](#metadata-update-semantics)
    - [Transient entities](#transient-entities)    
    - [Notification triggering](#notification-triggering)
    - [Notification Messages](#notification-messages)
    - [Custom Notifications](#custom-notifications)
    - [Oneshot Subscription](#oneshot-subscription)
    - [Covered subscriptions](#covered-subscriptions)
    - [Subscriptions based in alteration type](#subscriptions-based-in-alteration-type)
    - Pagination (including current [Ordering Results](#ordering-results))

**Review by fgalan — APPROVED** [review]
LGTM!

It have been a large work but the final result is *outstanding* :)

**Pull request merged**
